const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, '../data/aleatoriedades.csv');

const personagens = [
  // Profissões cotidianas (1-100)
  "Bombeiro", "Chef de cozinha", "Detetive", "Turista perdido", "Avó rabugenta", "Astronauta", "Professor distraído",
  "Pirata aposentado", "Cientista maluco", "Vendedor ambulante", "Dona de casa estressada", "Pedreiro filosófico",
  "Lanterninha de cinema", "Flanelinha", "Porteiro fofoqueiro", "Garçom apressado", "Taxista tagarela", "Vendedor de coxinha",
  "Padeiro madrugador", "Professor de autoescola", "Síndico autoritário", "Motorista de ônibus cansado", "Feirante animado",
  "Carteiro corajoso", "Encanador desastrado", "Dentista nervoso", "Veterinário alérgico a bichos", "Enfermeira hiperativa",
  "Advogado dramático", "Arquiteto perfeccionista", "Eletricista medroso", "Jardineiro poético", "Mecânico desconfiado",
  "Barbeiro hipnótico", "Caixa de supermercado lento", "Entregador de aplicativo com pressa", "Motorista de Uber conselheiro",
  "Jornalista investigativo", "Fotógrafo focado", "Personal trainer gritador", "Tatuador indeciso", "Manicure fofoqueira",
  "Cozinheiro de meias", "Lixeiro cantor", "Coveiro bem-humorado", "Gari dançarino", "Costureira detalhista",
  "Pintor de parede alucinando", "Zelador mal-humorado", "Segurança sonolento", "Salva-vidas que não sabe nadar",
  "Ascensorista tagarela", "Guia turístico inventativo", "Cerimonialista em pânico", "Organizador de festas surpresa",
  "Apresentador de TV apelativo", "Repórter de rua molhado", "Locutor de rádio rouco", "DJ de festa infantil",
  "Sommelier de água", "Crítico gastronômico chato", "Barista gourmet", "Garçom de rodízio", "Churrasqueiro orgulhoso",
  "Mestre de obras bravo", "Instalador de ar-condicionado", "Chaveiro mágico", "Dedetizador assustado", "Vidraceiro delicado",
  "Sapateiro antigo", "Relojoeiro paciente", "Estofador calado", "Guinchador amigável", "Vendedor de colchão",
  "Corretor de imóveis insistente", "Gerente de banco estressado", "Caixa eletrônico humano", "Contador desesperado",
  "Consultor de moda extravagante", "Cabeleireiro das estrelas", "Maquiador dramático", "Esteticista tagarela",
  "Massagista forte demais", "Fisioterapeuta exigente", "Nutricionista brava", "Psicólogo que só escuta",
  "Coach de autoajuda sem noção", "Professor de física quântica", "Professora de matemática rígida", "Professor de educação física",
  "Professor de história apaixonado", "Professor de artes excêntrico", "Inspetor de escola bravo", "Diretor de escola severo",
  "Merendeira carinhosa", "Monitor de perua escolar", "Bibliotecário exigente de silêncio", "Auxiliar de limpeza cantora",

  // Pop culture, filmes, desenhos e séries (101-200)
  "Harry Potter", "Darth Vader", "Batman", "Sherlock Holmes", "Coringa", "Jack Sparrow", "Barbie", "Shrek", "Homem-Aranha",
  "Wandinha Addams", "Gandalf", "Mario Bros", "Donatello Tartaruga Ninja", "Pikachu", "SpongeBob Bob Esponja", "Patrick Estrela",
  "Seu Sirigueijo", "Lula Molusco", "Chaves", "Kiko", "Seu Madruga", "Dona Florinda", "Professor Girafales", "Chapolin Colorado",
  "Scooby-Doo", "Salsicha", "Velma", "Freddie Mercury cover", "Michael Jackson imitador", "Elvis Presley", "Mickey Mouse",
  "Pateta", "Piu-Piu", "Frajola", "Pica-Pau maluco", "Tom do Tom & Jerry", "Jerry o rato", "Homer Simpson", "Bart Simpson",
  "Lisa Simpson", "Seu Burns", "Marge Simpson", "Buzz Lightyear", "Woody", "WALL-E", "Kung Fu Panda Po", "Shrek no pântano",
  "Burro do Shrek", "Gato de Botas", "Elsa de Frozen", "Olaf boneco de neve", "Moana", "Maui sem anzol", "Aladdin",
  "Gênio da Lâmpada", "Jafar", "Simba", "Timão", "Pumba", "Cinderela apressada", "Branca de Neve com sono", "Capitão América",
  "Homem de Ferro", "Thor sem martelo", "Hulk bravo", "Viúva Negra", "Doutor Estranho", "Deadpool engraçado", "Wolverine irritado",
  "Pantera Negra", "Groogu Baby Yoda", "Mandaloriano", "Luke Skywalker", "Yoda sábio", "Chewbacca gritando", "R2-D2 apitando",
  "Neo do Matrix", "Morpheus misterioso", "Gollum do Senhor dos Anéis", "Legolas arqueiro", "Gimli anão", "Willy Wonka",
  "Minion amarelo", "Gru do Meu Malvado Favorito", "Sonic veloz", "Tails raposa", "Dr. Eggman", "Naruto correndo", "Goku Sayajin",
  "Vegeta orgulhoso", "Sailor Moon", "Luffy Chapéu de Palha",

  // Históricos, literatura e mitologia (201-300)
  "Napoleão Bonaparte", "Cleópatra", "Albert Einstein", "Julius Caesar", "Leonardo da Vinci", "William Shakespeare", "Charlie Chaplin",
  "Dom Pedro I", "Princesa Isabel", "Tiradentes", "Santos Dumont", "Lampião", "Maria Bonita", "Zumbi dos Palmares", "Getúlio Vargas",
  "Machado de Assis", "Clarice Lispector", "Monteiro Lobato", "Anita Garibaldi", "Padre Cícero", "Alexandre o Grande",
  "Joana d'Arc", "Isaac Newton", "Galileu Galilei", "Marie Curie", "Beethoven surdo", "Mozart criança", "Vincent van Gogh",
  "Pablo Picasso", "Frida Kahlo", "Salvador Dalí", "Sigmund Freud", "Charles Darwin", "Karl Marx", "Adam Smith", "Sócrates",
  "Platão filosofando", "Aristóteles", "Pitágoras", "Arquimedes no banho", "Júlio Verne", "H.G. Wells", "Agatha Christie",
  "Edgar Allan Poe", "Dom Quixote", "Sancho Pança", "Robin Hood", "Rei Arthur", "Merlim mago", "Guinevere", "Conan o Bárbaro",
  "Hércules forte", "Zeus com raio", "Poseidon molhado", "Hades bravo", "Afrodite vaidosa", "Atena sábia", "Apolo músico",
  "Medusa brava", "Minotauro confuso", "Centauro elegante", "Fênix renascida", "Thor nórdico", "Loki trapaceiro", "Odin caolho",
  "Anúbis egípcio", "Esfinge enigmática", "Faraó sarcástico", "Cleópatra banhando em leite", "Gladiador romano", "Centurião cansado",
  "Espartano gritando", "Viking sem machado", "Capitão corsário", "Ninja silencioso", "Samurai honrado", "Geisha graciosa",
  "Imperador chinês", "Monge tibetano em meditação", "Cavalheiro medieval", "Bufão do rei", "Alquimista atrapalhado",
  "Cangaceiro poeta", "Boiadeiro solitário", "Bandeirante perdido", "Índio guerreiro", "Pajé sábio", "Curupira com pés pra trás",
  "Saci Pererê", "Mula sem Cabeça assustada", "Iara sereia", "Caipora protetora", "Boto cor-de-rosa", "Negrinho do Pastoreio",
  "Cabeça de Cuia", "Mapinguari",

  // Tipos urbanos e figuras cotidianas cômicas (301-400)
  "Tio do pavê", "Primo invejoso", "Sogra implicante", "Cunhado folgado", "Vizinha fofoqueira de janela", "Blogueira de beleza",
  "Influenciador fitness", "Gamer viciado", "Otaku emocionado", "Hipster do café", "Faria Limer de colete", "Coach ontológico",
  "Cringe de meia idade", "Tia do Zap desinformada", "Jovem místico com cristais", "Vegano militante", "Sommelier de cerveja artesanal",
  "Crossfiteiro lesionado", "Hater de internet", "Troll de comentários", "Nerd de HQ", "Cosplayer atrasado", "Fã incondicional de diva pop",
  "Pagodeiro dos anos 90", "Rocker saudosista", "Sertanejo universitário", "Funkeiro de caixa de som", "Rapper de batalha de rima",
  "Hippie de praia", "Paz e amor natureba", "Mãe de pet exagerada", "Pai de planta dedicado", "Acumulador compulsivo",
  "Minimalista radical", "Mão de vaca extremo", "Ostentador sem dinheiro", "Comprador compulsivo", "Fura-fila profissional",
  "Passageiro sem passagem", "Carona chato", "Piloto de fuga amador", "Ciclista de domingo", "Skatista sem skate",
  "Surfista de asfalto", "Maratonista de esteira", "Neta que ajuda a avó", "Sobrinho que arruma o Wi-Fi", "Amigo da onça",
  "Falso magro", "Atleta de fim de semana", "Pé frio de apostas", "Azarado profissional", "Sortudo que achou dinheiro",
  "Sonhador de mega-sena", "Hipnotizador amador", "Mágico de ilusão sem truque", "Mestre de RPG rígido", "Jogador de bingo viciado",
  "Velhinha do tricot", "Tio da sinuca", "Apostador de jogo do bicho", "Churrasqueiro do condomínio", "Organizador de bolão",
  "Rainha do camarote", "Promoter de balada", "Segurança de porta de show", "Pipoqueiro da praça", "Baiana do acarajé",
  "Vendedor de algodão doce", "Padeiro de sonho", "Garçom de chopp", "Barman de caipirinha", "Atendente de telemarketing",
  "Operador de suporte técnico", "Atendente de conveniência", "Frentista simpático", "Lavador de carro detalhista",
  "Mecânico de bicicleta", "Vendedor de consórcio", "Corretor de seguros pessimista", "Fiscal da prefeitura", "Agente de trânsito bravo",
  "Guarda municipal severo", "Policial de filme americano", "Detetive particular de traição", "Espião atrapalhado",
  "Agente secreto aposentado", "Segurança de shopping", "Vigilante noturno", "Técnico da operadora de TV", "Entregador de gás",
  "Vendedor de pamonha do carro de som", "Vendedor de ovo da cartela", "Vendedor de churros",

  // Fantásticos, absurdo, ficção e surreal (401-500)
  "Vampiro vegetariano", "Fantasma tímido", "Alienígena disfarçado", "Super-herói atrapalhado", "Mágico de festa infantil",
  "Robô com mau contato", "Monstro embaixo da cama", "Zombie vegetariano", "Lutador de sumô", "Astronauta sem capacete",
  "ET de Varginha", "Papai Noel de shopping", "Sereia fora d'água", "Ninja desajeitado", "Cozinheiro que odeia comida",
  "Duende de jardim falante", "Gnomo rabugento", "Fada madrinha confusa", "Bruxa de chapéu torto", "Lobisomem em noite de lua cheia",
  "Cérbero cão de 3 cabeças", "Dragão com falta de ar", "Gárgula de pedra falante", "Unicórnio com insônia", "Pégaso sem asas",
  "Múmia com coceira", "Frankenstein romântico", "Drácula sem dentes", "Maconheiro de galáxia", "Ciborgue enferrujado",
  "Androide com pane de sistema", "Inteligência Artificial que virou humana", "Viajante do tempo perdido no passado",
  "Homem invisível que espirra muito", "Telepatante que só ouve pensamentos idiotas", "Mutante com superpoder de esquentar água",
  "Homem-Elástico travado nas costas", "Homem de Pedra com rinite", "Velocista que tropeça na própria sombra",
  "Capitão de nave espacial sem combustível", "Imperador intergaláctico mimado", "Caçador de recompensas espacial",
  "Bounty hunter estressado", "Alien com 4 braços e nenhuma coordenação", "Cão espacial de capacete", "Gato gigante telepatador",
  "Monstro da Fossa das Marianas", "Pé Grande tímido", "Monstro do Lago Ness de férias", "Chupacabra vegetariano",
  "Abominável Homem das Neves com frio", "KRAKEN pequenininho", "Besta do apocalipse fofinha", "Anjo da guarda distraído",
  "Demônio burocrático", "Espírito zombeteiro de biblioteca", "Poltergeist de cozinha", "Geninho de lâmpada que dá 1 desejo",
  "Fauno tocador de flauta", "Sátiro dançarino", "Minotauro com claustrofobia", "Centauro que quer ser jóquei",
  "Ciclope que precisa de óculos", "Gorgona que usa óculos escuros", "Troll de ponte cobrando pedágio", "Ogro vegetariano",
  "Elfo de Papai Noel em greve", "Duende irlandês sem pote de ouro", "Leprechaun sem sorte", "Espantalho que tem medo de passarinhos",
  "Boneco de neve no verão", "Homem de Palha em chamas", "Homem de Lata precisando de óleo", "Leão covarde",
  "Espantalho sem cérebro", "Homem de Madeira Pinóquio mentiroso", "Barão de Münchhausen exagerado", "Rei Midas que toca em tudo",
  "Doutor Frankenstein triste", "Monstro de Marshmallow gigante", "Blob de gelatina ambulante", "Planta carnívora falante",
  "Alien verde de 3 olhos", "Caçador de fantasmas sem equipamento", "Investigador do sobrenatural assustado",
  "Exorcista que tem medo de escuro", "Vampiro que tem pavor de sangue", "Lobisomem alérgico a pelos", "Fantasma com medo de altura",
  "Múmia alérgica a poeira", "Sereia que não sabe nadar", "Astronauta que tem labirintite", "Piloto de OVNI sem carteira",
  "Cientista do futuro sem memória", "Manipulador do tempo atrasado", "Mago de gelo no deserto", "Feiticeiro de fogo na água",
  "Bebê gênio de fralda", "Zumbi vegetariano fã de salada", "ET baixinho com antenas", "Maconheiro de galáxia perdido",
  "Duende sapateiro sem cola", "Minotauro com rinite", "Gênio de lâmpada sem lâmpada", "Feiticeira estagiária",
  "Sereia de água doce", "Lobisomem careca", "Múmia sem faixa", "Dragão com soluço", "Anão minerador cantando",
  "Elfo da floresta alérgico a pólen", "Troll de internet presencial", "Capa invisível que não esconde o pé",
  "Robô de limpeza consciente", "Drone fotógrafo intrometido", "Ciborgue com bateria fraca", "Clone que acha que é o original",
  "Cientista de laboratório maluco", "Viajante dimensional sem bússola", "Alquimista transformando ferro em plástico"
];

const localizacoes = [
  "Praia", "Elevador", "Consultório médico", "Cozinha de restaurante", "Estação espacial", "Casamento", "Vagão de metrô",
  "Floresta", "Escritório", "Praça de alimentação", "Bar da esquina", "Enterro", "Lanterninha de cinema", "Micareta",
  "Sauna pública", "Restaurante chique", "Planeta Marte", "Embaixo d'água", "Fila do banco", "Padeiro madrugador",
  "Salão de beleza", "Ponto de ônibus", "Provador de loja", "Cartório", "Oficina mecânica", "Reunião de condomínio",
  "Exame de laboratório", "Aula de pilates", "Show de rock pesado", "Festa de aniversário infantil", "Topo do Monte Everest",
  "Dentro de um vulcão", "Nave espacial em chamas", "Ilha deserta", "Interior de uma baleia", "Castelo assombrado",
  "Fossa das Marianas", "Dimensão paralela", "Dentro do estômago de um monstro", "Feira livre de domingo", "Balada sertaneja",
  "Tribunal de justiça", "Vaca atolada na lama", "Asilo de idosos", "Canteiro de obras", "Circo mambembe",
  "Estádio de futebol lotado", "Biblioteca silenciosa", "Parque de diversões abandonado", "Aquário municipal", "Spa de luxo",
  "Supermercado no horário de pico", "Bunker subterrâneo", "Museu de arte moderna", "Camarim de teatro", "Heliponto",
  "Cabine de teleférico", "Concessionária de carros", "Coquetel de negócios", "Cemitério de aviões", "Piscina pública lotada",
  "Submarino atômico", "Lava-rápido automático", "Lanchonete 24 horas", "Padaria de bairro", "Açougue", "Peixaria",
  "Banca de jornal", "Farmácia de plantão", "Lotérica no dia da Mega da Virada", "Pet shop", "Veterinária",
  "Estúdio de tatuagem", "Barbearia retrô", "Loja de 1 real", "Shopping center no Natal", "Praça de jogos de tabuleiro",
  "Quadra de society", "Academia de musculação cheia", "Pista de skate", "Parque de cachorros", "Coreto da praça matriz",
  "Rodoviária de madrugada", "Aeroporto com voo atrasado", "Estação de trem no pico", "Ponto de táxi", "Terminal de ônibus",
  "Posto de combustível", "Conveniência do posto", "Borracharia 24h", "Estacionamento rotativo", "Depósito de material de construção",
  "Loja de móveis", "Loja de sapatos", "Floricultura", "Joalheria de shopping", "Sebo de livros usados", "Loja de antiguidades",
  "Brechó de roupas", "Mercado municipal", "Sacolão de frutas", "Churrascaria rodízio",
  "Recepção de hotel 5 estrelas", "Cozinha industrial", "Refeitório de empresa", "Sala de reunião de diretoria",
  "Call center lotado", "Sala de servidores com ar-condicionado trincando", "Laboratório de química", "Estúdio de rádio ao vivo",
  "Estúdio de gravação de podcast", "Bastidores de desfile de moda", "Plato de gravação de novela", "Camarim de cantor famoso",
  "Sala de autópsia do IML", "Delegacia de polícia", "Cela de cadeia", "Sala de interrogatório", "Posto de saúde de bairro",
  "UTI de hospital", "Sala de cirurgia", "Maternidade", "Ambulância em emergência", "Corpo de bombeiros", "Quartel militar",
  "Campo de treinamento militar", "Torre de controle de aeroporto", "Cabine de avião comercial", "Convés de navio cargueiro",
  "Sala de máquinas de navio", "Farol isolado na costa", "Usina hidrelétrica", "Usina nuclear", "Plataforma de petróleo",
  "Mina de carvão subterrânea", "Pedreira de extração de mármore", "Usina de reciclagem de lixo", "Aterro sanitário",
  "Estação de tratamento de esgoto", "Laboratório de biologia molecular", "Observatório astronômico", "Antena de transmissão de TV",
  "Centro de distribuição de encomendas", "Galpão de estoque", "Almoxarifado central", "Arquivos mortos da prefeitura",
  "Câmara de vereadores", "Plenário do senado", "Embaixada diplomática", "Consulado", "Cartório de notas", "Junta comercial",
  "Repartição pública federal", "Posto do INSS", "Posto do Poupatempo", "Detran no dia de vistoria", "Receita federal",
  "Sala de audiência de conciliação", "Escritório de advocacia refinado", "Escritório de contabilidade", "Agência de publicidade descolada",
  "Startup de tecnologia com pufes", "Empresa de investimentos", "Bolsa de valores gritando", "Casa de câmbio",
  "Cofre forte de banco", "Carro forte", "Guarita de segurança", "Sala de monitoramento de câmeras", "Posto de fiscalização de fronteira",
  "Alfandega de aeroporto", "Centro de treinamento de astronautas", "Base militar secreta", "Bunker de autoridade",
  "Sala de guerra presidencial", "Escola de aviação", "Simulador de voo", "Autoescola baliza", "Escola de marinha",
  "Academia de polícia", "Escola de bombeiros", "Centro de adestramento de cães", "Escola de gastronomia", "Oficina de marcenaria",
  "Oficina de serralheria", "Oficina de funilaria", "Estaleiro de navios", "Fábrica de automóveis", "Fábrica de chocolates",
  "Fábrica de brinquedos", "Cervejaria artesanal", "Destilaria de cachaça", "Vinícola no meio do vinhedo", "Cooperativa agrícola",
  "Camarote de carnaval na Sapucaí", "Trio elétrico em Salvador", "Festa junina de quermesse", "Roda de samba na calçada",
  "Festival de música no lamaçal", "Show de heavy metal na grade", "Rave no meio do mato", "Balada sertaneja VIP",
  "Baile funk na quadra", "Festa de formatura de faculdade", "Baile de debutante de 15 anos", "Festa de bodas de ouro",
  "Chá de bebê surpresa", "Chá de revelação de sexo", "Despedida de solteiro em Las Vegas", "Casamento na praia sob chuva",
  "Recepção de casamento com buffet falhando", "Almoço de domingo em família", "Churrasco na laje", "Piquenique no parque",
  "Acampamento na montanha", "Fogueira de acampamento", "Trilha na mata fechada", "Passeio de barco a vela", "Passeio de lancha",
  "Passeio de caiaque no rio", "Descida de rafting na corredeira", "Salto de paraquedas no ar", "Voo de asa delta",
  "Voo de balão de ar quente", "Parque aquático no tobogã", "Piscina de ondas", "Parque de diversões na roda gigante",
  "Montanha-russa no ponto mais alto", "Trem fantasma", "Carrinho de bate-bate", "Casa dos espelhos", "Stand de tiro ao alvo",
  "Circo sob a lona", "Picadeiro de circo", "Bastidores de circo", "Teatro municipal no palco", "Plateia de teatro lotada",
  "Foyer de teatro", "Cinema na fila da pipoca", "Sessão de cinema 3D", "Drive-in de carros", "Show de stand-up comedy",
  "Encontro de cosplayers em convenção", "Torneio de e-sports na arena", "Campeonato de xadrez em silêncio", "Torneio de poker",
  "Casa de bingo clandestina", "Cassino de luxo", "Mesa de roleta", "Corrida de cavalos no jóquei", "Arquibancada de estádio de futebol",
  "Vip box de estádio", "Vestiário de time de futebol", "Gramado de estádio antes do jogo", "Circuito de Fórmula 1 nos boxes",
  "Pista de atletismo", "Ginásio de basquete", "Piscina olímpica", "Quadra de tênis de saibro", "Pista de patinação no gelo",
  "Estação de esqui na neve", "Teleférico de montanha gelada", "Trilha de mountain bike", "Pista de motocross",
  "Pista de kart", "Rodeio de touros", "Exposição agropecuária", "Feira de ciências de escola", "Feira de tecnologia e inovação",
  "Bienal do livro lotada", "Vernissage de galeria de arte", "Leilão de arte contemporânea", "Museu de história natural ao lado do dinossauro",
  "Planetário no escuro", "Jardim botânico na estufa de plantas", "Zoológico na jaula do leão", "Aquário gigante no túnel dos tubarões",
  "Parque temático de dinossauros", "Resort all-inclusive na piscina", "Cruzeiro marítimo no deque principal",
  "Sótão empoeirado de casa antiga", "Porão escuro com teias de aranha", "Garagem lotada de caixas", "Lavanderia de apartamento pequena",
  "Varanda gourmet com churrasqueira", "Sacada de apartamento no 20º andar", "Telhado de casa em dia de chuva",
  "Jardim dos fundos com gramado", "Horta comunitária de bairro", "Quarto de bebê recém-nascido", "Quarto de adolescente bagunçado",
  "Quarto de casal com cama desfeita", "Banheiro pequeno com chuveiro queimado", "Banheira de hidromassagem",
  "Cozinha americana com balcão", "Dispensa de mantimentos lotada", "Corredor estreito de cortiço", "Escada de emergência do prédio",
  "Hall de entrada de edifício", "Portaria de condomínio residencial", "Playground de prédio", "Quadra poliesportiva de condomínio",
  "Salão de festas de prédio após o evento", "Sala de jogos com sinuca", "Sauna de condomínio", "Piscina de condomínio",
  "Deck de madeira de casa de praia", "Chácara de aluguel no fim de semana", "Sítio com galinheiro", "Curral de fazenda com vacas",
  "Pasto de gado", "Pomar de jabuticabas", "Casa de campo com lareira", "Cabana de madeira na floresta", "Casa na árvore infantil",
  "Palafita na beira do rio", "Oca indígena", "Tenda de acampamento no escuro", "Trailer de viagem estacionado", "Motorhome na estrada",
  "Casa flutuante no lago", "Iglu de gelo no ártico", "Tenda de beduíno no deserto", "Castelo de areia gigante na praia",
  "Casinha de cachorro no quintal", "Galinheiro barulhento", "Estábulo de cavalos", "Canil de adestramento", "Gatil de gatos",
  "Colmeia gigante de abelhas", "Formigueiro sob a terra", "Ninho de pássaros no topo da árvore", "Caverna de morcegos",
  "Buraco de tatu", "Toca de coelho profunda", "Aquário de peixes dourados", "Gaiola de passarinho", "Terrário de iguanas",
  "Orquidário de estufa", "Plantação de milho em milharal", "Plantação de café", "Canavial alto", "Plantação de girassóis",
  "Plantação de morangos", "Horta orgânica", "Parreiral de uvas", "Vinha de vinhos", "Olival de azeitonas",
  "Pomar de laranjas", "Castanhal na Amazônia", "Seringal de borracha", "Pântano cheio de mosquitos", "Manguezal na maré baixa",
  "Dunas de areia caindo", "Oásis com palmeiras no deserto", "Cachoeira com poço fundo", "Beira de rio com piranhas",
  "Lagoa azul cristalina", "Praia deserta de surfe", "Recife de corais no fundo do mar", "Abismo de penhasco",
  "Caverna com estalactites", "Gruta subterrânea com ilha", "Vulcão adormecido na cratera", "Geyser jorrando água quente",
  "Geleira derretendo", "Fjord norueguês congelado", "Tundra gelada", "Estepes da Sibéria", "Savana africana com leões",
  "Jungle tropical fechada", "Deserto de sal gigante", "Cânion profundo", "Vale dos reis", "Pirâmide do Egito por dentro",
  "Nave-mãe alienígena pairando sobre a Terra", "Base espacial na Lua", "Colônia humana em Marte", "Estação de pesquisa em Titã",
  "Anéis de Saturno em órbita", "Buraco negro absorvendo luz", "Supernova explodindo no espaço", "Nave geracional à deriva",
  "Laboratório secreto sob o gelo da Antártida", "Cidade submersa de Atlântida", "Triângulo das Bermudas no meio da tempestade",
  "Centro da Terra com dinossauros vivos", "Mundo em miniatura dentro de uma gota d'água", "Dimensão do limbo onde o tempo parou",
  "Reino das nuvens sobre um pé de feijão", "Castelo voador suspenso no ar", "Cidade futurista do ano 3000 com carros voadores",
  "Metrópole cyberpunk cheia de neon e chuva", "Mundo pós-apocalíptico estilo Mad Max", "Terra devastada por zumbis",
  "Bunker atômico no dia do fim do mundo", "Arca de Noé durante o dilúvio", "Jardim do Éden com a serpente", "Torre de Babel em construção",
  "Labirinto do Minotauro sem saída", "Monte Olimpo na casa dos deuses", "Submundo de Hades no rio Estire", "Valhala dos vikings em banquete",
  "Asgard sobre a ponte arco-íris", "El Dorado a cidade de ouro perdida", "Shangri-La nas montanhas sagradas", "Camelot na Távola Redonda",
  "Floresta encantada de Sherwood", "País das Maravilhas no chá do Chapeleiro", "Terra do Nunca voando com Peter Pan",
  "Cidade dos Esmeraldas em Oz", "Hogwarts na sala do grande salão", "Beco Diagonal nas lojas mágicas", "Prisão de Azkaban na tempestade",
  "Mordor na Montanha da Perdição", "Condado dos Hobbits na toca", "Taverna medieval cheia de orcs e elfos", "Masmorra de castelo com correntes",
  "Torre da princesa com dragão guardião", "Ponte do troll cobrando pedágio", "Cemitério maldito em noite de lua cheia",
  "Navio fantasma do Cinto Holandês", "Ilha do Tesouro com mapa escondido", "Caverna dos 40 Ladrões abrindo", "Lâmpada mágica por dentro",
  "Ventre da baleia do Pinóquio", "Fábrica de chocolates do Willy Wonka na sala do rio de chocolate", "Oficina do Papai Noel no Polo Norte",
  "Trens no Polo Express em velocidade máxima", "Matriz do código caindo em tela verde", "Dentro de um jogo de videogame em 8-bits",
  "Dentro da mente humana na sala de memórias", "Sonho dentro de outro sonho", "Linha do tempo alternativa desmoronando",
  "Estação de trem plataforma 9 3/4", "Voo de tapete mágico sobre o deserto", "Submarino do Capitão Nemo Nautilus",
  "Laboratório do Doutor Frankenstein no dia da tempestade", "Castelo do Conde Drácula na Transilvânia", "Pirâmide maia no momento do eclipse",
  "Templo de Indiana Jones com a pedra gigante rolante", "Ruínas de Pompéia durante a erupção do Vesuvius", "Coliseu de Roma em dia de combate",
  "Arena de gladiadores em Roma", "Partenon na Grécia Antiga", "Muralha da China sob ataque", "Taj Mahal ao pôr do sol",
  "Estátua da Liberdade dentro da tocha", "Torre Eiffel no topo da antena", "Big Ben dentro das engrenagens do relógio",
  "Canais de Veneza em um passeio de gôndola", "Catedral de Notre Dame no campanário do Corcunda", "Palácio de Versalhes no Salão dos Espelhos",
  "Kremlin em Moscou na neve", "Casa Branca no Salão Oval", "Pentágono na sala de inteligência", "Área 51 no galpão dos alienígenas",
  "CERN no Acelerador de Partículas", "Nasa na sala de lançamento de foguetes", "Vale do Silício na garagem da primeira Apple",
  "Hollywood na calçada da fama", "Las Vegas na avenida dos cassinos à noite", "Times Square no ano novo sob chuva de papel",
  "Carnaval do Rio no meio da bateria da escola de samba", "Maracanã no minuto final da final da Copa do Mundo", "Cristo Redentor sob a névoa",
  "Teatro Amazonas no meio da floresta", "Pelourinho em Salvador sob o som dos tambores", "Cataratas do Iguaçu na garganta do diabo",
  "Fernando de Noronha na praia do Sancho", "Lençóis Maranhenses nas lagoas de chuva", "Amazônia na copa das árvores gigantes",
  "Pantanal com jacarés ao redor", "Chapada dos Veadeiros no vale da lua", "Cavernas de PETAR no escuro total", "Serra do Rio do Rastro nas curvas",
  "Fila do bandejão universitário", "Balcão de informações de aeroporto", "Vagão de trem bala a 300km/h", "Cabine de trator na colheita",
  "Cabine de guindaste a 100 metros de altura", "Poço de petróleo no deserto", "Restaurante giratório no topo de torre",
  "Quarto de motel temático", "Sauna seca de clube tradicional", "Vestiário de academia após a aula", "Lavanderia self-service",
  "Lanchonete drive-thru no horário de pico", "Fila de vacinação em posto", "Estande de feira imobiliária", "Stand de degustação no mercado",
  "Sessão espírita", "Terreiro de umbanda", "Templo budista no silêncio", "Convento de freiras isolado",
  "Mosteiro nas alturas da Grécia", "Cemitério no dia de Finados", "Velório com seresta", "Necrotério municipal",
  "Praça de alimentação de shopping domingo", "Lojas de souvenirs na Disney", "Teleférico do Pão de Açúcar", "Mirante da serra do mar",
  "Balsa entre ilhas", "Trapiche de pescadores", "Decks de marina de iates", "Estúdio de yoga silencioso",
  "Estúdio de pilates com aparelhos", "Ringue de boxe iluminado", "Octógono de artes marciais", "Pista de boliche luminosa",
  "Salão de jogos de fliperama arcade", "Escape room temático fechado", "Sala de karaokê privativa", "Camarote de show sertanejo",
  "Bastidores de desfile de fantasia", "Camarim de ópera de gala", "Foyer de teatro histórico", "Plateia de estúdio de audição",
  "Sala de ensaio de orquestra", "Estúdio de dublagem acústico", "Bandejão de universidade pública", "Refeitório de escola infantil",
  "Dormitório de albergue estudantil", "Recepção de pousada rústica", "Piscina térmica de hotel fazenda"
];

const filmesLivros = [
  "O Poderoso Chefão", "Titanic", "Star Wars: Uma Nova Esperança", "De Volta para o Futuro", "Matrix", "O Senhor dos Anéis: A Sociedade do Anel",
  "Harry Potter e a Pedra Filosofal", "Jurassic Park", "Os Vingadores", "Avatar", "Forrest Gump", "O Rei Leão", "Pulp Fiction",
  "Clube da Luta", "O Iluminado", "Gladiador", "Interestelar", "Inception (A Origem)", "O Silêncio dos Inocentes", "E.T. O Extraterrestre",
  "Tubarão", "De Volta para o Futuro II", "Psicose", "Casablanca", "A Lista de Schindler", "O Resgate do Soldado Ryan", "Batman: O Cavaleiro das Trevas",
  "O Grande Truque", "Coringa", "Os Bons Companheiros", "Taxi Driver", "Laranja Mecânica", "2001: Uma Odisséia no Espaço", "Blade Runner",
  "Alien, o Oitavo Passageiro", "O Exterminador do Futuro 2", "Indiana Jones e os Caçadores da Arca Perdida", "Rocky, um Lutador",
  "Rambo: Programado para Matar", "Top Gun: As Ases Indomáveis", "Dirty Dancing", "Curtindo a Vida Adoidado", "Os Caça-Fantasmas",
  "Meninas Malvadas", "As Branquelas", "Se Beber, Não Case!", "Superbad: É Hoje", "Shrek", "Shrek 2", "Toy Story", "Procurando Nemo",
  "Os Incríveis", "Monstros S.A.", "Divertida Mente", "Viva: A Vida é uma Festa", "Kung Fu Panda", "Como Treinar o Seu Dragão",
  "Meu Malvado Favorito", "Madagascar", "A Era do Gelo", "Ratatouille", "UP: Altas Aventuras", "WALL-E", "Moana", "Frozen: Uma Aventura Congelante",
  "Enrolados", "Zootopia", "A Bela e a Fera", "Aladdin", "A Pequena Sereia", "Mulan", "Pocahontas", "Hercules", "Tarzan",
  "Carros", "A Viagem de Chihiro", "Meu Amigo Totoro", "Kimi no Na wa (Your Name)", "Akira", "Ghost in the Shell", "O Castelo Animado",
  "Piratas do Caribe: A Maldição do Pérola Negra", "Homem de Ferro", "Capitão América: Guerra Civil", "Thor: Ragnarok", "Pantera Negra",
  "Guardiões da Galáxia", "Homem-Aranha: No Aranhaverso", "Doutor Estranho", "Logan", "Deadpool", "X-Men: Dias de um Futuro Esquecido",
  "O Espetacular Homem-Aranha", "Crepúsculo", "Jogos Vorazes", "Divergente", "Maze Runner", "A Culpa é das Estrelas", "Harry Potter e o Enigma do Príncipe",
  "O Hobbit: Uma Jornada Inesperada", "As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa", "Percy Jackson e o Ladrão de Raios",
  "O Código Da Vinci", "Anjos e Demônios", "Sherlock Holmes", "007: Cassino Royale", "007: Operação Skyfall", "Missão Impossível",
  "Velozes e Furiosos", "Velozes e Furiosos 5: Operação Rio", "John Wick", "Busca Implacável", "Duro de Matar", "Até o Último Homem",
  "1917", "Dunkirk", "Corações de Ferro", "Troia", "300", "Spartacus", "Braveheart (Coração Valente)",
  "Cidade de Deus", "Tropa de Elite", "Tropa de Elite 2", "Auto da Compadecida", "Central do Brasil", "Minha Mãe é uma Peça",
  "Que Horas Ela Volta?", "O Palhaço", "O Auto da Compadecida 2", "Bacurau", "O Cheiro do Ralo", "Lisbela e o Prisioneiro",
  "O Homem que Copiava", "Saneamento Básico, o Filme", "Meu Nome Não É Johnny", "Carandiru", "Dois Filhos de Francisco",
  "Se Eu Fosse Você", "De Pernas pro Ar", "Até que a Sorte nos Separe", "Tudo por um Popstar", "Turma da Mônica: Laços",
  "Cazuza: O Tempo Não Para", "Tim Maia", "Elis", "Chorão: Marginal Alado", "Marighella", "Hoje Eu Quero Voltar Sozinho",
  "Aquarius", "Bingo: O Rei das Manhãs", "Estrada do Diabo", "O Beijo da Mulher Aranha", "Dona Flor e Seus Dois Maridos",
  "Macunaíma", "Vidas Secas", "O Pagador de Promessas", "Terra em Transe", "Deus e o Diabo na Terra do Sol", "Pixote, a Lei do Mais Fraco",
  "Bye Bye Brasil", "Cabra Cego", "O Que É Isso, Companheiro?", "A Partilha", "O Casamento de Romeu e Julieta", "Durval Discos",
  "Amarelo Manga", "Madame Satã", "Cinema, Aspirinas e Urubus", "Boi Neon", "Tatuagem", "BR716", "Como Nossos Pais",
  "Benzinho", "A Vida Invisível", "Marte Um", "Pedágio", "Retratos Fantasmas", "Manas", "Caramuru: A Invenção do Brasil",
  "O Xangô de Baker Street", "Deus É Brasileiro", "Casa de Areia", "Desmundo", "Lula, o Filho do Brasil", "Chico Xavier",
  "Nosso Lar", "Kardec", "Os Dez Mandamentos: O Filme", "Cine Holliúdy", "O Shaolin do Sertão", "Cabras da Peste",
  "Um Suburbano Sortudo", "Os Farofeiros", "Tô Ryco!", "Muita Calma Nessa Hora", "Vai que Cola: O Filme", "Os Penetras",
  "Dom Casmurro", "Memórias Póstumas de Brás Cubas", "O Cortiço", "Vidas Secas (Livro)", "Grande Sertão: Veredas", "Capitães da Areia",
  "O Alquimista", "A Hora da Estrela", "Macunaíma (Livro)", "O Quinze", "Iracema", "Senhora", "O Guarani", "Triste Fim de Policarpo Quaresma",
  "São Bernardo", "Fogo Morto", "O Tempo e o Vento", "Olhai os Lírios do Campo", "A Causa das Secretas", "Noite na Taverna",
  "Saramandaia", "E Não Sobrou Nenhum", "Assassinato no Expresso do Oriente", "O Sol É para Todos",
  "1984", "Admirável Mundo Novo", "Fahrenheit 451", "O Apanhador no Campo de Centeio", "O Sol Também Se Levanta", "O Velho e o Mar",
  "Cem Anos de Solidão", "O Amor nos Tempos do Cólera", "Crônica de uma Morte Anunciada", "A Metamorfose", "O Processo",
  "O Castelo", "Ensaio sobre a Cegueira", "O Evangelho segundo Jesus Cristo", "As Intermitências da Morte", "O Nome da Rosa",
  "Foucault e o Pêndulo", "Corações Sujos", "A Revolução dos Bichos", "Laranja Mecânica (Livro)", "Drácula", "Frankenstein",
  "O Médico e o Monstro", "O Retrato de Dorian Gray", "O Morro dos Ventos Uivantes", "Jane Eyre", "Orgulho e Preconceito",
  "Razão e Sensibilidade", "Emma", "Grandes Esperanças", "Oliver Twist", "Um Conto de Duas Cidades", "Moby Dick",
  "As Aventuras de Huckleberry Finn", "As Aventuras de Tom Sawyer", "O Conde de Monte Cristo", "Os Miseráveis", "O Corcunda de Notre-Dame",
  "Dom Quixote de La Mancha", "A Divina Comédia", "A Odisséia", "A Ilíada", "Édipo Rei", "Hamlet", "Macbeth", "Romeu e Julieta",
  "O Mercador de Veneza", "Sonho de uma Noite de Verão", "A Tempestade", "O Rei Lear", "Fausto", "Guerra e Paz", "Anna Karenina",
  "Crime e Castigo", "Os Irmãos Karamázov", "O Idiota", "Noites Brancas", "O Mestre e Margarida", "Doutor Jivago", "Lolita",
  "O Iluminado (Livro)", "It: A Coisa", "Carrie, a Estranha", "Misery: Louca Obsessão", "Sob a Redoma", "O Apanhador de Sonhos",
  "Dança da Morte", "A Torre Negra: O Pistoleiro", "O Hobbit", "O Senhor dos Anéis: O Retorno do Rei", "O Silmarillion",
  "As Crônicas de Nárnia", "O Leão, a Feiticeira e o Guarda-Roupa", "A Bússola de Ouro", "O Nome do Vento", "A Sabedoria do Medo",
  "O Temor do Sábio", "O Caminho dos Reis", "A Guerra dos Tronos", "A Fúria dos Reis", "A Tormenta de Espadas", "O Festim dos Corvos",
  "A Dança dos Dragões", "O Aprendiz de Assassino", "Duna", "Messias de Duna", "Filhos de Duna", "Neuromancer", "Fundação",
  "Fundação e Império", "Segunda Fundação", "Eu, Robô", "2001: Uma Odisséia no Espaço (Livro)", "O Guia do Mochileiro das Galáxias",
  "O Restaurante no Fim do Universo", "A Vida, o Universo e Tudo Mais", "Até Mais, e Obrigado pelos Peixes", "Quase Sem Dano",
  "O Homem do Castelo Alto", "Androides Sonham com Ovelhas Elétricas?", "Solaris", "Cama de Gato",
  "Harry Potter e a Câmara Secretinha", "Harry Potter e o Prisioneiro de Azkaban", "Harry Potter e o Cálice de Fogo",
  "Harry Potter e a Ordem da Fênix", "Harry Potter e as Relíquias da Morte", "O Ladrão de Raios", "O Mar de Monstros",
  "A Maldição do Titã", "A Batalha do Labirinto", "O Último Olímpico", "Jogos Vorazes: Em Chamas", "Jogos Vorazes: A Esperança",
  "A Cantiga dos Pássaros e das Serpentes", "Divergente", "Insurgente", "Convergente", "Maze Runner: Correr ou Morrer",
  "A Culpa é das Estrelas", "Cidades de Papel", "Quem é Você, Alasca?", "O Ódio que Você Semeia", "Vermelho, Branco e Sangue Azul",
  "É Assim que Acaba", "É Assim que Começa", "Os Sete Maridos de Evelyn Hugo", "Daisy Jones & The Six", "Leitura de Verão",
  "Loucos por Livros", "A Hipótese do Amor", "A Razão do Amor", "Teto para Dois", "O Povo do Ar: O Príncipe Cruel",
  "Corte de Espinhos e Rosas", "Corte de Névoa e Fúria", "Corte de Asas e Ruína", "Trono de Vidro", "Cidade dos Ossos",
  "As Crônicas de Amor e Ódio", "De Sangue e Cinzas", "Quarta Asa", "Iron Flame", "Heartstopper", "Persepolis", "Maus",
  "Watchmen", "V de Vingança", "Sandman: Prelúdios e Noturnos", "Batman: O Cavaleiro das Trevas Retorna", "Batman: A Piada Mortal",
  "Superman: Entre a Foice e o Martelo", "Guerra Civil (HQ)", "Manhwa Solo Leveling", "One Piece (Mangá)", "Naruto Shippuden",
  "Attack on Titan (Shingeki no Kyojin)", "Demon Slayer (Kimetsu no Yaiba)", "Jujutsu Kaisen", "Death Note", "Dragon Ball Z",
  "My Hero Academia (Boku no Hero)", "Fullmetal Alchemist: Brotherhood", "Hunter x Hunter", "Bleach", "Tokyo Ghoul",
  "Chainsaw Man", "Spy x Family", "Neon Genesis Evangelion", "Cowboy Bebop", "Berserk", "Vinland Saga", "JoJo's Bizarre Adventure",
  "Sailor Moon", "Saint Seiya (Cavaleiros do Zodíaco)", "Yu Yu Hakusho", "InuYasha", "Monster", "Code Geass", "Steins;Gate",
  "Sword Art Online", "Demon Slayer: Mugen Train", "Your Name", "O Tempo com Você", "Suzume", "A Voz do Silêncio",
  "Akira (Mangá)", "Nausicaä do Vale do Vento", "Princesa Mononoke", "A Viagem de Chihiro", "Meu Amigo Totoro",
  "O Castelo Animado", "Ponyo", "O Serviço de Entregas da Kiki", "Vidas ao Vento", "O Menino e a Garça",
  "Matrix Resurrections", "Avatar: O Caminho da Água", "Gladiador II", "Duna: Parte 2", "Oppenheimer", "Barbie (Filme)",
  "Spider-Man: Sem Volta Para Casa", "Top Gun: Maverick", "The Batman", "Guardians of the Galaxy Vol. 3", "Super Mario Bros. O Filme",
  "Wicked", "Moana 2", "Divertida Mente 2", "Deadpool & Wolverine", "Coringa: Delírio a Dois", "Alien: Romulus",
  "Beetlejuice Beetlejuice", "Nosferatu", "Pobres Criaturas", "Assassinos da Lua das Flores", "A Baleia", "TÁR",
  "Tudo em Todo o Lugar ao Mesmo Tempo", "Os Banshees de Inisherin", "Drive My Car", "Parasita", "Roma", "Green Book: O Guia",
  "A Forma da Água", "Moonlight: Sob a Luz do Luar", "La La Land: Cantando Estações", "Spotlight: Segredos Revelados",
  "Birdman", "12 Anos de Escravidão", "Argo", "O Artista", "O Discurso do Rei", "Guerra ao Terror", "Quem Quer Ser um Milionário?",
  "Onde os Fracos Não Têm Vez", "Os Infiltrados", "Crash: No Limite", "Menina de Ouro", "O Senhor dos Anéis: O Retorno do Rei",
  "Amélie Poulain", "Clube dos Cinco", "Curtindo a Vida Adoidado", "Sociedade dos Poetas Mortos", "Gênio Indomável",
  "O Show de Truman", "Brilho Eterno de uma Mente sem Lembranças", "A Origem", "O Grande Hotel Budapeste", "Moonrise Kingdom",
  "Whiplash: Em Busca da Perfeição", "La Haine (O Ódio)", "Os Intocáveis", "Cinema Paradiso", "A Vida É Bela",
  "O Pianista", "O Profissional (Léon)", "Bastardos Inglórios", "Django Livre", "Os Oito Odiados", "Kill Bill: Volume 1", "Kill Bill: Volume 2",
  "Cães de Aluguel", "Scarface", "O Chefão II", "Os Bons Companheiros", "Cassino", "O Irlandês", "Era Uma Vez em Hollywood",
  "Zack Snyder's Justice League", "Mulher-Maravilha", "Aquaman", "Shazam!", "O Homem de Aço", "Batman v Superman",
  "Guardiões da Galáxia Vol. 2", "Vingadores: Era de Ultron", "Vingadores: Guerra Infinita", "Vingadores: Ultimato",
  "Capitão América: O Soldado Invernal", "Thor: Amor e Trovão", "Homem-Aranha: De Volta ao Lar", "Homem-Aranha: Longe de Casa",
  "Black Widow", "Shang-Chi e a Lenda dos Dez Anéis", "Eternos", "Doutor Estranho no Multiverso da Loucura", "Wonka",
  "Godzilla e Kong: O Novo Império", "Furiosa: Uma Saga Mad Max", "Bad Boys: Até o Fim", "Planeta dos Macacos: O Reinado",
  "Garfield: Fora de Casa", "Meu Malvado Favorito 4", "Um Lugar Silencioso: Dia Um", "Twisters", "Os Osso da Morte",
  "Sonic 3: O Filme", "Mufasa: O Rei Leão", "Gladiador 2", "Coringa 2", "Paddington no Peru", "Kraven o Caçador"
];

const adjetivosCaracteristicas = [
  "Tagarela", "Tímido", "Hiperativo", "Ciumento", "Pessimista", "Otimista ingênuo", "Autoritário", "Debochado", "Dramático",
  "Perfeccionista", "Preguiçoso", "Nervoso", "Esquecido", "Avarento (Mão de vaca)", "Estressado", "Fofoqueiro", "Desconfiado",
  "Perdidamente apaixonado", "Supersticioso", "Hipocondríaco", "Orgulhoso", "Vaidoso", "Modesto demais", "Melancólico",
  "Euforico", "Rebelde", "Conservador", "Místico", "Sarcástico", "Cínico", "Ingênuo", "Sábio", "Maluco Beleza", "Frio e calculista",
  "Emocionado", "Corajoso", "Medroso", "Ansioso", "Calmo até demais", "Irritadíssimo", "Teimoso", "Flexível", "Carismático",
  "Antipático", "Sedutor", "Desajeitado", "Elegante", "Rústico", "Filosófico", "Prático", "Sonhador", "Apressado", "Paciente",
  "Impaciente", "Desorganizado", "Metódico", "Esquisito", "Excêntrico", "Extrovertido", "Introvertido", "Sensível", "Insensível",
  "Manipulador", "Sincero até demais", "Mentiroso compulsivo", "Honesto", "Leal", "Traiçoeiro", "Impulsivo", "Cauteloso",
  "Vingativo", "Perdoador", "Carinhoso", "Frio", "Grossos", "Gentil", "Mal-humorado", "Bem-humorado", "Sem noção", "Sensato",
  "Conselheiro", "Critico", "Dramático de novela", "Triunfante", "Derrotado", "Nostálgico", "Futurista", "Desmemoriado",
  "Curioso", "Indiferente", "Compulsivo", "Controlador", "Desencanado", "Trágico", "Cômico", "Misterioso", "Enigmático",
  "Transparente", "Duas caras", "Fiel", "Volúvel", "Persistente", "Dedicado", "Desistente", "Competitivo", "Pacífico",
  "Agressivo", "Passivo-agressivo", "Ironico", "Solícito", "Egoísta", "Altruísta", "Materialista", "Espiritualizado",
  "Cético", "Fanático", "Idealista", "Realista", "Pessimista extremo", "Sonhador incurável", "Nostálgico obsessivo",
  "Alto e desengonçado", "Baixinho enfezado", "Fortão de academia", "Magricela", "Lento de movimentos", "Apressado de ritmo",
  "Com voz esganiçada", "Com voz grave de locutor", "Que fala sussurrando", "Que fala gritando", "Que gesticula demais",
  "Com tique nervoso no olho", "Com mania de coçar o nariz", "Que anda mancando", "Que anda nas pontas dos pés", "Com postura ereta militar",
  "Com ombros caídos de cansaço", "Que respira fundo toda hora", "Que ri de tudo", "Que chora por qualquer coisa", "Com miopia sem óculos",
  "Com labirintite", "Com soluço ininterrupto", "Com rinite atacada", "Com coceira nas costas", "Com frio excessivo",
  "Com calor insuportável", "Com fome de leão", "Com sono profundo", "Com insônia", "Com tontura leve", "Com cheiro de perfume forte",
  "Com cheiro de chulé", "Com terno chique", "De pijama e pantufas", "De óculos escuros de noite", "De chapéu estranho",
  "Com maquiagem borrada", "Com roupa ao contrário", "Com sapato apertado", "Com mochila pesadíssima", "Com guarda-chuva aberto",
  "Com sacolas nas duas mãos", "Descalço no asfalto", "Com luvas de boxe", "Com capacete de moto", "Com avental sujo de molho",
  "Com gravata torta", "Com peruca colorida", "Com bigode postiço caindo", "Com capa de super-herói", "Com manchas de tinta nas mãos",
  "Com toalha na cabeça", "Com curativo na testa", "Com gesso no braço", "Com muletas", "De patins no pé", "De salto alto desconfortável",
  "Com terno de lantejoulas", "De fantasia de dinossauro", "De maiô de natação", "De casaco de pele no verão", "Com bermuda florida e chinelo",
  "Com paletó rasgado", "Com coroa de plástico", "Com cetro real", "Com luvas de silicone", "Com máscara de proteção",
  "Com protetor auricular", "Com fones de ouvido gigantes", "Com medalhas no peito", "Com faixa de campeão", "Com crachá virado",
  "Com avental de cozinha", "Com uniforme de entregador", "Com roupa de mergulho", "Com roupa de astronauta", "De túnica medieval",
  "De kimono de karatê", "De tutu de bailarina", "Com pijama de bolinhas", "De camisa de time de futebol", "Com lenço no pescoço",
  "Com monóculo no olho", "Com cachimbo na boca", "Com leque se abanando", "Com bengala elegante", "Com binóculo no pescoço",
  "Com apito no peito", "Com prancha de surfe embaixo do braço", "Com raquete de tênis", "Com violão nas costas", "Com mala de rodinhas",
  "Com carrinho de feira", "Com papagaio no ombro", "Com gato no colo", "Com cachorro na coleira", "Com gaiola de passarinho",
  "Desesperado por ajuda", "Em transe hipnótico", "Sob efeito de muita cafeína", "Bêbado de cidra", "Com dor de dente terrível",
  "Com azia forte", "Com câimbra na perna", "Com dor nas costas de idoso", "Perdido sem GPS", "Atrasado para a noiva",
  "Procurando o banheiro urgente", "Tentando esconder um segredo", "Achando que está num filme de terror", "Achando que está sendo filmado",
  "Achando que todos são alienígenas", "Convencido de que é um fantasma", "Achando que ganhou na Mega-Sena", "Com medo de germes",
  "Com medo de altura", "Com pavor de palhaço", "Com medo de escuro", "Com medo de borboletas", "Achando que é invisível",
  "Achando que tem superpoderes", "Fingindo ser muito rico", "Fingindo ser gringo", "Fingindo ser cego", "Fingindo ser o chefe",
  "Fingindo ser um médico renomado", "Fingindo ser detetive secreto", "Que não lembra o próprio nome", "Que acha que está no ano 1800",
  "Que acha que está no espaço", "Com dor de barriga repentina", "Tentando não dar risada em velório", "Tentando segurar o espirro",
  "Com coceira num lugar difícil", "Com chiclete grudado no sapato", "Com fiapo de manga no dente", "Com meia furada no calcanhar",
  "Com etiquetas da roupa pinicando", "Com etiqueta de preço pendurada na roupa", "Com zíper da calça aberto", "Com mancha de café na camisa",
  "Com a calça rasgada atrás", "Com dois sapatos do mesmo pé", "Com meias trocadas", "Com cabelo totalmente desarrumado",
  "Com pasta de dente no queixo", "Com batom nos dentes", "Com rímel escorrido no rosto", "Com fita crepe no óculos quebrados",
  "Com voz rouca pós-show", "Com zumbido constante no ouvido", "Com cisco no olho", "Com nó na garganta de emoção",
  "Com solavancos de soluço", "Com enjoo de viagem", "Com insolação de praia", "Com congelamento nos dedos",
  "Com bolhas no pé de caminhar", "Com câimbra nos dedos da mão", "Com braço dormindo", "Com a perna formigando",
  "Com torcicolo no pescoço", "Com dor de cabeça enxaqueca", "Com falta de ar de ansiedade", "Com batimentos cardíacos acelerados",
  "Com borboletas no estômago de nervoso", "Com nó no estômago de medo", "Com mãos suando frio", "Com joelhos tremendo",
  "Com dentes batendo de frio", "Com queixo caído de choque", "Com olhos arregalados de susto", "Com boca aberta de espanto",
  "Com sorriso amarelo de vergonha", "Com rosto vermelho de vergonha", "Com olhar vago de brisa", "Com olhar fixo assustador",
  "Com queixo levantado de arrogância", "Com sobrancelha levantada de desconfiança", "Com biquinho de birra", "Com braços cruzados de pirraça",
  "Com mãos na cintura de bronca", "Com dedo em riste de acusação", "Com mãos na cabeça de desespero", "Com mãos no rosto de vergonha",
  "Com punhos fechados de raiva", "Com palmas abertas de rendição", "Com joelhos no chão pedindo perdão", "Com postura de lutador",
  "Convencido de que é um repolho", "Com a voz de um vilão de desenho", "Que só se comunica por rimas", "Que faz efeito sonoro pra tudo que faz",
  "Que acha que a vida é um musical", "Que narra a própria vida em voz alta", "Que acha que é um gato preso num corpo humano",
  "Que só consegue andar de lado como caranguejo", "Que acha que tudo ao redor é feito de chocolate", "Que tem pavor da palavra 'Batata'",
  "Que acha que o mediador é Deus", "Que se assusta com a própria sombra", "Que aplaude tudo que os outros dizem",
  "Que pede desculpas a cada 3 segundos", "Que acha que é um agente secreto em missão", "Que acha que está num comercial de xampu",
  "Que tenta vender coisas imaginárias", "Que só fala usando jargões de futebol", "Que só fala usando termos médicos complicados",
  "Que fala como um pirata do século XVII", "Que fala como um locutor de leilão", "Que fala como uma dublagem dos anos 80",
  "Que fala como um personagem de novela mexicana", "Que fala como um robô com bateria fraca", "Que responde tudo cantando ópera",
  "Que responde tudo com perguntas profundas", "Que acha que é o rei da Inglaterra", "Que acha que é um bebê gigante",
  "Que acha que está flutuando no espaço", "Que acha que o chão é lava vulcânica", "Que acha que os atores são estátuas",
  "Que só anda dando passos de dança", "Que faz mímica involuntária de tudo", "Que confunde todas as palavras com comida",
  "Que tem surtos de risada maléfica", "Que só fala sussurrando segredos inúteis", "Que acha que é um alienígena disfarçado",
  "Que tem medo de pessoas de chapéu", "Que acha que é um dinossauro T-Rex com braços curtos", "Que imita os movimentos do parceiro 2 segundos depois",
  "Que acha que é um jurado de reality show", "Que dá notas de 0 a 10 pra tudo", "Que tenta adivinhar o futuro de forma errada",
  "Que traz um amigo imaginário para a cena", "Que acha que a plateia são zumbis", "Que tenta ensinar etiqueta em momentos absurdos",
  "Que fala em código secreto que ninguém entende", "Que só fala usando nomes de frutas", "Que acha que o microfone é uma coxinha",
  "Que tem pavor de barulho de papel", "Que comemora cada palavra dita como um gol", "Que acha que está no Faustão no 'Ô Loco Meu'",
  "Que acha que está no Silvio Santos pedindo 'Quem quer dinheiro'", "Que narra a cena como um documentário do National Geographic",
  "Que fala como um comentarista esportivo chato", "Que fala como um pastor de TV de madrugada", "Que fala como um leiloeiro de gado",
  "Que fala como um comandante de avião na turbulência", "Que fala como um DJ de rádio de charme", "Que fala como um garçom de restaurante fino",
  "Que fala como um dublador de filme de ação", "Que fala como um vilão de anime gritando golpes", "Que fala como um mestre de artes marciais sábio",
  "Que fala como uma vovó oferecendo bolo", "Que fala como uma criança de 4 anos birrenta", "Que fala como um adolescente revoltado",
  "Que fala como um coach quântico de reprogramação", "Que fala como um fiscal de vigilância sanitária", "Que fala como um perito criminal de CSI",
  "Que fala como um repórter de cobertura de tragédia", "Que fala como um apresentador de circo animado", "Que fala como um guia de museu entediado",
  "Que fala como um vendedor de colchão de feira", "Que fala como um cobrador de van de lotação", "Que fala como um síndico irritado em reunião",
  "Que fala como um juiz no STF lendo voto longo", "Que fala como um leiloeiro de arte refinado", "Que fala como um pescador contando mentira",
  "Que fala como um turista gringo tentando falar português", "Que fala como um alienígena aprendendo palavras humanas",
  "Que fala como um robô com inteligência limitada", "Que fala como um aplicativo de mapa recalculando rota",
  "Que fala como uma mensagem gravada de telemarketing", "Que fala como um locutor de propaganda de remédio nos termos finais",
  "Que fala como um locutor de rodeio no momento do pião", "Que fala como um narrador de corrida de cavalos", "Que fala como um juiz de boxe",
  "Que fala como um treinador de boxe no corner", "Que fala como um apresentador de jornal bancada de TV", "Que fala como um meteorologista",
  "Que fala como um crítico de arte esnobe", "Que fala como um chef Michelin bravo", "Que fala como um árbitro de futebol usando VAR",
  "Que fala como um capitão de navio pirata em tempestade", "Que fala como um mágico que errou o truque", "Que fala como um hipnotizador amador",
  "Que fala como um ventríloquo brando com o boneco", "Que fala como um dublador de desenho animado clássico", "Que fala como um monge tibetano",
  "Com medo de espelhos", "Com pavor de sombras", "Com trauma de despertador", "Que acha que tudo é uma pegadinha",
  "Que fala dando gargalhadas de vilão", "Que só responde com frases de efeito de filmes", "Que tenta ler as mãos dos outros",
  "Que se acha um influenciador de 10 milhões de seguidores", "Que faz pose de modelo a cada 5 segundos", "Que só anda de costas",
  "Com risada contagiante", "Que se assusta fácil", "Super competitivo", "Com pose de astro do rock", "Que só fala gírias dos anos 80",
  "Que lê pensamentos errados", "Que acha que é a pessoa mais famosa do mundo", "Que anda dançando mambo", "Que fala igual ao Yoda",
  "Com mania de arrumar o cabelo", "Com tique de estalar os dedos", "Que chora quando fica feliz", "Que ri quando fica brabo",
  "Desconfiado de conspirações", "Acreditando em ETs na terra", "Sentindo frio nos pés", "Tentando disfarçar bocejos",
  "Fazendo propaganda de si mesmo", "Com fobia de gravatas", "Com pavor de chiclete", "Acreditando ser de origem nobre",
  "Falando rápido demais pra acompanhar", "Fazendo pausa dramática a cada frase", "Com gargalhada alta e escandalosa",
  "Piscando um olho só sem querer", "Que não aguenta ver poeira", "Que quer arrumar a roupa dos outros",
  "Com hábito de estalar o pescoço", "Sempre oferecendo conselho não solicitado",
  "Sempre olhando no relógio", "Perguntando o significado de tudo", "Segurando o riso com a mão na boca",
  "Imitando o sotaque de quem fala", "Olhando pros lados com desconfiança", "Sempre checando o bolso",
  "Ajustando o óculos a cada fala", "Dando risadinha no final de cada frase", "Dizendo que já sabia de tudo",
  "Tentando adivinhar o final das frases dos outros", "Acreditando em qualquer mentira contada", "Fazendo sinal de joia pra tudo",
  "Sempre oferecendo ajuda desajeitada", "Inventando estatísticas na hora", "Falando como se estivesse num comercial",
  "Com medo de pisar nas linhas do chão", "Sempre achando que esqueceu o fogão ligado", "Tirando fotos imaginárias de tudo",
  "Com hábito de concordar balançando a cabeça", "Fazendo suspense antes de responder", "Dizendo 'e digo mais!' o tempo todo",
  "Dizendo 'complicado isso aí' em toda pausa", "Chamando todo mundo de 'campeão'", "Usando termos de internet na vida real",
  "Aconselhando todos a beberem mais água", "Perguntando o signo de todo mundo", "Que não consegue guardar um segredo por 5 segundos",
  "Que fala alto achando que está sussurrando", "Que tenta dar abraço em desconhecidos", "Que só responde com letras de música",
  "Que acha que tudo é um teste surpresa", "Que fica procurando onde está o microfone", "Que tenta achar defeito em tudo",
  "Que elogia excessivamente coisas simples", "Que faz drama quando perde um objeto", "Que acha que é o protagonista da cena",
  "Que dá conselhos de relacionamentos sem nunca ter namorado", "Que inventa regras de etiquetas inexistentes",
  "Que acha que o ambiente é mal assombrado", "Que tenta adivinhar o signo pelo formato do rosto",
  "Que vive achando moedas no chão", "Que conta histórias de parentes distantes", "Que usa ditados populares errados",
  "Que tenta resolver conflitos com abraços", "Que se emociona com comerciais de TV", "Que tem medo de bonecos de pelúcia",
  "Que fala com objetos inanimados", "Que tenta imitar barulhos de animais", "Que faz suspense para revelar coisas banais",
  "Que tem orgulho de coisas totalmente irrelevantes", "Que vive prometendo presentes que nunca entrega",
  "Que dança levemente enquanto escuta os outros", "Que morde o lábio inferior ao pensar",
  "Que estala a língua antes de discordar", "Que ajeita a gola da camisa a cada 10 segundos",
  "Que pisca o olho cúmplice sem necessidade", "Que usa expressões em inglês erradas",
  "Que finge anotações no bloco de notas invisível", "Que repete a última palavra dita pelo parceiro",
  "Que faz contagem regressiva para falar", "Que abre muito os braços ao explicar algo simples"
];

console.log(`Personagens: ${personagens.length}`);
console.log(`Localizações: ${localizacoes.length}`);
console.log(`Filmes / Livros: ${filmesLivros.length}`);
console.log(`Adjetivos / Características: ${adjetivosCaracteristicas.length}`);

let csvOutput = "Personagem,Localizacao,Filme / Livro,Adjetivo / Característica\n";

for (let i = 0; i < 500; i++) {
  const p = (personagens[i] || 'Personagem').replace(/,/g, '');
  const l = (localizacoes[i] || 'Local').replace(/,/g, '');
  const fl = (filmesLivros[i] || 'Filme').replace(/,/g, '');
  const ac = (adjetivosCaracteristicas[i] || 'Característica').replace(/,/g, '');

  csvOutput += `"${p}","${l}","${fl}","${ac}"\n`;
}

fs.writeFileSync(csvPath, csvOutput, 'utf8');
console.log(`CSV 100% preenchido com 500 itens únicos em TODAS as 4 colunas!`);
