const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, '../data/aleatoriedades.csv');
const rawCSV = fs.readFileSync(csvPath, 'utf8');

function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') inQuotes = false;
      else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.some((v) => v !== '')) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }

  const header = rows.shift().map((h) => h.trim());
  return {
    header,
    rows: rows
      .filter((r) => r.some((v) => v.trim() !== ''))
      .map((r) => Object.fromEntries(header.map((h, i) => [h, (r[i] || '').trim()])))
  };
}

const { header, rows } = parseCSV(rawCSV);

const frases = [
  // Frases cotidianas e absurdas do dia a dia (1-100)
  "Acho que engoli a minha própria língua.",
  "Você tem um cigarro aí?",
  "A guerra intergalática está chegando!",
  "Quem colocou maionese no meu sapato?",
  "Nunca diga isso perto do meu gato.",
  "Eu jurava que o farol estava verde.",
  "Esqueci como se senta numa cadeira.",
  "Alguém aqui sabe desativar uma bomba?",
  "Não olha agora, mas tem um pinguim atrás de você.",
  "Você por acaso viu a minha dentadura?",
  "Promete que não vai rir de mim?",
  "Se a polícia perguntar, estávamos no cinema.",
  "Comi a última fatia e não me arrependo.",
  "Isso não é um micro-ondas, é um portal!",
  "Meu tornozelo acabou de fazer um barulho estranho.",
  "Você tem certeza de que este cogumelo é comestível?",
  "Eu sou o verdadeiro herdeiro desse trono!",
  "Sinto cheiro de pneu queimado.",
  "Quem é você e o que fez com o meu papagaio?",
  "Não me toca que eu tô eletcutado!",
  "Acho que meu dente da frente tá mole.",
  "Pelo amor de Deus, fecha essa janela!",
  "Esqueci a senha do meu próprio cérebro.",
  "Você se importa se eu dormir aqui só dez minutinhos?",
  "Pensei que essa festa fosse à fantasia.",
  "Ninguém sai dessa sala até o anel aparecer!",
  "Minha mãe mandou te dar um abraço.",
  "Eu nunca vi tanto repolho na minha vida.",
  "Você ouviu esse zumbido ou eu tô ficando louco?",
  "Sempre soube que você não era flor que se cheire.",
  "O botão vermelho diz para NÃO apertar!",
  "Alguém trouxe um guarda-chuva de reserva?",
  "Minha perna tá dormindo há três horas.",
  "Não acredito que você vendeu o nosso fogão!",
  "Você fala como se soubesse o que tá fazendo.",
  "A calça rasgou no meio do agachamento.",
  "Tem como devolver a minha dignidade?",
  "Tira a mão da minha empadinha!",
  "Alguém me lembra qual é o meu próprio nome?",
  "Isso aqui não é suco de maracujá!",
  "Sinto que estamos sendo observados por pombos.",
  "Eu só vim aqui pra comer coxinha.",
  "Não se mexe, tem uma abelha no seu nariz!",
  "Você tem cinco reais pra me emprestar até 2030?",
  "A porta tá trancada por fora!",
  "Acho que perdi meu umbigo.",
  "Isso vai doer mais em você do que em mim.",
  "Seu cachorro acabou de latir em francês?",
  "Eu juro que tentei ser uma boa pessoa.",
  "Alguém desliga essa música pelo amor do guarda!",
  "Cadê o meu outro pé de meia?",
  "Você não acha que a lua tá perto demais hoje?",
  "Tenho quase certeza de que esse peixe piscou pra mim.",
  "Coloquei sal no café em vez de açúcar.",
  "Não me olha com essa cara de julgamento!",
  "Eu não paguei o boleto de energia.",
  "Por favor, fala que isso é um pesadelo.",
  "A pizza caiu virada pra baixo no tapete.",
  "Você por acaso sabe falar com fantasmas?",
  "Esqueci o bolo no forno faz quatro dias.",
  "Minha pressão baixou só de ver a sua cara.",
  "Quem foi que soltou esse pum?",
  "Vou fingir que não ouvi o que você acabou de dizer.",
  "Você tá usando o meu sabonete no cabelo?",
  "Isso não é sangue, é molho de tomate!",
  "Acho que a gente pegou o ônibus errado.",
  "Me dá dez segundos pra inventar uma desculpa.",
  "Você tem certeza de que o freio tá funcionando?",
  "Não me venha com choro de crocodilo!",
  "Toda vez que chove meu joelho estala.",
  "Cadê a chave que tava aqui agora pouco?",
  "Se liga, o Wi-Fi caiu de novo!",
  "Você pisou no meu calcanhar de propósito!",
  "Não dá pra conversar com quem tá de pijama.",
  "Quem deixou esse melão no meu travesseiro?",
  "Eu vi quando você escondeu o brigadeiro.",
  "Não abre essa geladeira de jeito nenhum!",
  "Nossa, como seu cabelo tá diferente hoje!",
  "Eu pensei que você sabia dirigir!",
  "Diz pra mim que esse barulho foi só o vento.",
  "Minha mãe disse que eu sou especial.",
  "Essa cueca não é minha!",
  "Se o chefe descobrir, tamo frito.",
  "Você fala demais pra quem não sabe nada.",
  "Desliga a luz que a luz tá cara!",
  "Você quer que eu chore ou que eu surte?",
  "Acho que comi sabão sem querer.",
  "Essa conversa tá ficando muito estranha.",
  "Perdi o chão e nem foi por paixão.",
  "Você tem coragem de olhar no meu olho?",
  "Alguém avisa que a reunião já acabou!",
  "Vou contar até três...",
  "Tem um ET na minha lavanderia!",
  "Eu nem queria estar aqui para começo de conversa.",
  "Cuidado com o degrau que não existe!",
  "Tira esse chapéu que tá me dando agonia.",
  "Sinto que minha alma saiu do corpo e voltou.",
  "Quem colocou detergente na minha sopa?",
  "Você tá me confundindo com outra pessoa!",
  "O elevador tá subindo rápido demais!",

  // Perguntas estranhas e inusitadas (101-200)
  "Você já tentou lamber o próprio cotovelo?",
  "Será que a gravidade tá funcionando direito hoje?",
  "Por que você tá me encarando desse jeito?",
  "Você acha que os peixes sentem sede?",
  "Posso ficar com o seu pão de alho?",
  "Você por acaso trouxe um dinossauro na bolsa?",
  "Por que o mundo tá de ponta-cabeça?",
  "Quem te deu permissão pra ser tão chato?",
  "Você prefere ser um pato ou um cavalo?",
  "Por que tem uma galinha dentro do guarda-roupa?",
  "Você já viu um fantasma de óculos escuros?",
  "Será que o espaço cheira a queimado?",
  "Você tem certeza de que a terra é me redonda?",
  "Por que você tá vestindo duas meias esquerdas?",
  "Você acha que eu tenho cara de palhaço?",
  "Quem é que come melancia com sal?",
  "Você se lembra de onde a gente se conheceu?",
  "Será que as plantas sentem dor de cabeça?",
  "Você pode segurar esse abacaxi pra mim?",
  "Por que a sua sombra tá se mexendo sozinha?",
  "Você trouxe a chave do cofre secreta?",
  "Por que você nunca me ouve quando eu falo?",
  "Será que é tarde demais pra mudar de vida?",
  "Você prefere perder um pé ou um braço?",
  "Por que tem um sapato dentro da geladeira?",
  "Você já tentou conversar com uma parede?",
  "Será que o futuro já aconteceu?",
  "Por que todo mundo tá me olhando assim?",
  "Você tem medo de privada entupida?",
  "Por que você tá sussurrando se tamo sozinhos?",
  "Será que a minha voz é chata assim mesmo?",
  "Você lembra o que fez no verão de 2012?",
  "Por que você comprou cinquenta quilos de sabão?",
  "Você acha que o mundo vai acabar hoje?",
  "Será que a gente pode recomeçar do zero?",
  "Por que tem um buraco no teto do seu quarto?",
  "Você por acaso é parente do prefeito?",
  "Será que o Papai Noel paga imposto de renda?",
  "Por que você não atendeu as minhas quarenta ligações?",
  "Você se importa se eu me sentar no chão?",
  "Por que você tá sorrindo desse jeito macabro?",
  "Será que meu espelho tá me enganando?",
  "Você trouxe a poção mágica que eu pedi?",
  "Por que tem um gato miando na sua mochila?",
  "Você me ama ou só gosta da minha comida?",
  "Será que alienígenas gostam de pagode?",
  "Por que você tá de casaco no meio do verão?",
  "Você prefere lutar contra um urso ou dez cachorros?",
  "Por que a porta do seu guarda-roupa bateu?",
  "Será que eu deixei a torneira aberta?",
  "Você acha que eu fico bem de bigode?",
  "Por que tem um pato de borracha na sua sopa?",
  "Você se lembra da nossa promessa de infância?",
  "Será que os pássaros são robôs da prefeitura?",
  "Por que você tá correndo se ninguém tá te perseguindo?",
  "Você acha que a vida é um jogo de videogame?",
  "Por que você tá me oferecendo essa coxinha suspeita?",
  "Será que a minha avó era uma espiã?",
  "Você tem medo de barata voadora?",
  "Por que tem uma melancia no meio da sala?",
  "Você já viu a lua ficar verde?",
  "Será que a gente tá numa pegadinha da TV?",
  "Por que você tá usando óculos de natação?",
  "Você acha que o tempo tá passando mais rápido?",
  "Por que o seu cachorro tá me encarando com raiva?",
  "Será que a sopa de ontem tava estragada?",
  "Você trouxe o mapa do tesouro ou esqueceu?",
  "Por que você tá cantando em espanhol?",
  "Você acha que eu tenho cara de quem se importa?",
  "Será que as estrelas estão caindo?",
  "Por que tem uma luva de boxe no seu colo?",
  "Você acredita em amor à primeira vista?",
  "Por que você tá segurando essa frigideira?",
  "Será que o restaurante tá aberto a essa hora?",
  "Você acha que a gente vai conseguir fugir?",
  "Por que tem um macaco no telhado?",
  "Você prefere voar ou ser invisível?",
  "Por que você tá me pedindo desculpas?",
  "Será que aquele homem ali é um ciborgue?",
  "Você lembra onde a gente estacionou o carro?",
  "Por que o sol tá brilhando tanto hoje?",
  "Você acha que o café tá forte demais?",
  "Por que você tá escondendo as mãos nas costas?",
  "Será que a polícia já tá vindo?",
  "Você tem coragem de pular daqui?",
  "Por que tem um envelope vermelho na minha mesa?",
  "Você acha que eu tô ficando maluco?",
  "Por que você nunca aceita os meus conselhos?",
  "Será que o meu sapato tá pequeno demais?",
  "Você trouxe o dinheiro do resgate?",
  "Por que o teto tá gotejando suco de laranja?",
  "Você acha que a gente devia ter virado à esquerda?",
  "Por que o seu celular tá apitando sem parar?",
  "Será que a professora notou que eu dormi?",
  "Você prefere frio congelante ou calor extremo?",
  "Por que você tá usando meias diferentes?",
  "Você acha que o mundo precisa de mais amor ou de mais pizza?",
  "Por que você tá me olhando com essa cara de choque?",
  "Será que a gente tá no filme errado?",
  "Você tem certeza de que isso é legal perante a lei?",

  // Frases dramáticas e exageradas de novela/cinema (201-300)
  "Eu nunca mais vou olhar na sua cara!",
  "Você destruiu tudo o que construímos juntos!",
  "Saia da minha casa e leve as suas mentiras com você!",
  "Se você der mais um passo, eu juro que grito!",
  "Foi você... o tempo todo era você!",
  "Não me peça calma num momento como este!",
  "O nosso amor acabou naquele maldito jantar!",
  "Eu preferia ter morrido a ver essa cena!",
  "Você não tem coração, tem uma pedra no peito!",
  "Guardei esse segredo por mais de vinte anos!",
  "Olha bem pra mim e diz que você não me ama!",
  "O testamento era falso desde o começo!",
  "Eu dei os melhores anos da minha vida pra você!",
  "Você vai pagar por cada lágrima que eu derrubei!",
  "Esqueça o meu nome e finja que eu nunca existi!",
  "Tudo o que você disse era uma grande farsa!",
  "Você não passa de um covarde mascarado!",
  "Eu descobri a verdade sobre aquela noite no navio!",
  "Você trocou a nossa família por dinheiro!",
  "Nunca mais ouse pronunciar o nome da minha mãe!",
  "A máscara caiu, meu caro amigo!",
  "Eu vi quando você assinou aquele contrato obscuro!",
  "Você pode enganar a todos, mas não a mim!",
  "Tire essa aliança do dedo imediatamente!",
  "Nós fomos enganados pela pessoa em quem mais confiávamos!",
  "O que você fez com a verdadeira herdeira?",
  "Eu vou contar a todos o que você esconde naquele sótão!",
  "Não adianta implorar perdão de joelhos!",
  "O destino nos separou, mas a vingança nos uniu!",
  "Você roubou o meu sonho e a minha juventude!",
  "Essa empresa pertence à minha família por direito!",
  "Eu preferia viver na miséria a aceitar a sua esmola!",
  "A verdade vai aparecer quando a tempestade passar!",
  "Você jogou o nosso futuro na lata do lixo!",
  "Não toque em mim com essas mãos sujas de traição!",
  "Eu sei quem você é de verdade por trás desse sorriso!",
  "Você vai se arrepender do dia em que me conheceu!",
  "Nada do que você diga vai apagar o passado!",
  "Eu ouvi tudo o que você disse atrás da porta!",
  "A sua ganância destruiu o nosso império!",
  "Você vendeu a sua alma por um punhado de moedas!",
  "Eu nunca deveria ter confiado em alguém como você!",
  "O veneno que você preparou vai servir para você mesmo!",
  "Essa casa não é grande o suficiente para nós dois!",
  "Eu vou até o fim do mundo pra te colocar na cadeia!",
  "Você pensou que eu nunca iria descobrir a verdade?",
  "O dinheiro não pode comprar a honra que você perdeu!",
  "Eu renuncio a esse título e a toda essa falsidade!",
  "Você é a maior decepção da minha existência!",
  "A justiça tarda, mas ela vai te alcançar hoje!",
  "Eu vi o olhar de raiva no seu rosto!",
  "Você queimou as cartas antes que eu pudesse ler!",
  "O império dos seus pais vai falir em questão de dias!",
  "Você me usou como uma peça num jogo de xadrez!",
  "Eu dei o meu sangue por esse projeto!",
  "Nunca pensei que o meu próprio irmão fosse me trair!",
  "Você é o responsável por toda essa tragédia!",
  "A história vai te julgar como o vilão que você é!",
  "Eu abri mão da minha felicidade por sua causa!",
  "Você escondeu a certidão de nascimento por trinta anos!",
  "Eu vou rasgar esse documento na frente de todo mundo!",
  "A sua ganância não tem limites!",
  "Você manchou o nome da nossa família para sempre!",
  "Eu nunca vou aceitar esse casamento forçado!",
  "Você me jurou lealdade diante do altar!",
  "A verdade é dolorosa, mas vai libertar a todos nós!",
  "Você acha que pode me comprar com joias caras?",
  "Eu prefiro a morte à vergonha da derrota!",
  "Você escondeu as provas embaixo do próprio colchão!",
  "A nossa aliança foi quebrada no instante em que você mentiu!",
  "Eu assisti à sua ruína sem mover um único dedo!",
  "Você trocou a sua dignidade por um cargo político!",
  "A sua hora chegou e não há para onde fugir!",
  "Eu vou revelar tudo na coletiva de imprensa!",
  "Você destruiu a reputação da única pessoa que te amava!",
  "Essa herança carrega uma maldição secular!",
  "Eu não vou permitir que você toque num único centavo!",
  "Você foi a pior escolha da minha vida inteira!",
  "A traição veio de onde eu menos esperava!",
  "Eu vou recuperar o que é meu por direito de nascença!",
  "Você jogou o nosso nome na lama!",
  "A noite está escura, mas a minha vingança será luminosa!",
  "Você mentiu sobre o teste de DNA!",
  "Eu não sou o filho que você esperava que eu fosse!",
  "Você me transformou no monstro que você tanto temia!",
  "A sua ganância destruiu o amor da sua vida!",
  "Eu prefiro andar sozinho a caminhar com cobras!",
  "Você vendeu a empresa para os nossos maiores inimigos!",
  "A dor que eu sinto hoje será a sua dor amanhã!",
  "Eu vi a luz nos seus olhos apagar!",
  "Você trocou a verdade por uma mentira confortável!",
  "O sangue fala mais alto que qualquer contrato!",
  "Eu nunca vou me curvar diante da sua autoridade!",
  "Você foi a causa da minha maior ruína!",
  "A tempestade lá fora é nada comparada à raiva no meu peito!",
  "Você me deixou esperando na chuva por quatro horas!",
  "O passado voltou pra cobrar a sua dívida!",
  "Eu nunca vou perdoar o que você fez naquele verão!",
  "A farsa acabou, tire essa máscara de bonzinho!",
  "Você vendeu os meus sonhos pelo preço de uma banana!",

  // Confissões, fofocas e segredos surpresa (301-400)
  "Fui eu que comi o seu iogurte de morango.",
  "Na verdade, eu não sei nadar.",
  "Eu tenho um irmão gêmeo secreto morando no Sul.",
  "Eu finjo que entendo de vinho mas só olho o preço.",
  "Eu derrubei a sua jarra favorita e culpei o gato.",
  "Eu durmo com a luz do corredor acesa até hoje.",
  "Eu não sou formado em medicina, sou mágico!",
  "Eu usei a sua escova de dentes sem querer semana passada.",
  "Eu odeio a sua comida mas comia pra te agradar.",
  "Eu perdi o aluguel no jogo do bicho.",
  "Eu inventei que tinha alergia só pra não ir na sua festa.",
  "Eu sei quem roubou o dinheiro do cofrinho em 2015.",
  "Eu tenho pavor de borboletas Amarelas.",
  "Eu menti no meu currículo e não sei usar o Excel.",
  "Eu assisti todos os episódios sem você!",
  "Eu finjo que tô ouvindo música mas o fone tá desligado.",
  "Eu peguei a sua jaqueta emprestada e manchei de café.",
  "Eu sei o seu segredo mais obscuro!",
  "Eu troquei o seu shampoo por condicionador.",
  "Eu coloco ketchup na pizza de calabresa.",
  "Eu nunca li o livro que eu disse que amava.",
  "Eu escutei a sua conversa atrás da porta do banheiro.",
  "Eu tenho uma conta secreta com três reais.",
  "Eu finjo que sei falar inglês em reuniões.",
  "Eu quebrei o seu vaso de estimação e colar com cuspe.",
  "Eu mandei a mensagem pra pessoa errada!",
  "Eu sei quem é o verdadeiro pai do bebê!",
  "Eu tenho medo de escuro e durmo de fralda.",
  "Eu não fui trabalhar porque fiquei jogando videogame.",
  "Eu peguei o seu carro de madrugada e arranhei a porta.",
  "Eu comi a ração do cachorro pra ver se era boa.",
  "Eu finjo que sou surdo quando vêm me pedir dinheiro.",
  "Eu robava os docinhos da mesa antes da festa começar.",
  "Eu tenho uma coleção secreta de meias furadas.",
  "Eu inventei essa história toda pra te impressionar!",
  "Eu votei no candidato errado por engano.",
  "Eu esqueci o aniversário da minha própria mãe.",
  "Eu tô usando a sua senha do Netflix faz três anos.",
  "Eu sei de onde vem aquele cheiro estranho no quintal.",
  "Eu finjo que sei dançar salsa mas só mexo os ombros.",
  "Eu caí no golpe do bilhete premiado ontem.",
  "Eu perdi a sua aliança de noivado na praia!",
  "Eu não sou seu amigo, sou um espião contratado!",
  "Eu menti a minha idade a vida inteira.",
  "Eu tenho medo de palhaço de festa infantil.",
  "Eu troquei o sal pelo açúcar na receita da sua mãe.",
  "Eu sou o dono daquele perfil fake que te curte.",
  "Eu não sei andar de bicicleta até hoje.",
  "Eu gastei o dinheiro do condomínio em figurinhas.",
  "Eu sei qual é a combinação do cofre!",
  "Eu mandei um áudio de cinco minutos falando mal de você!",
  "Eu chorei assistindo o comercial de sabão em pó.",
  "Eu tenho um terceiro mamilo escondido.",
  "Eu menti que sabia cozinhar e pedi comida fora.",
  "Eu esqueci a minha própria data de nascimento.",
  "Eu durmo com um ursinho de pelúcia chamado Bob.",
  "Eu tenho nojo de chule mas o meu cheira mal.",
  "Eu derrubei o bolo de noivado no chão e montei de novo.",
  "Eu não sou seu primo de segundo grau de verdade!",
  "Eu peguei o seu carregador e não vou devolver.",
  "Eu coloco maionese no feijão escondido.",
  "Eu perdi a chave da casa dentro do bueiro.",
  "Eu finjo que tenho compromisso pra ir embora cedo.",
  "Eu tenho pavor de espelho no escuro.",
  "Eu sei quem riscou a pintura do seu carro!",
  "Eu não sei a tabuada do sete até hoje.",
  "Eu inventei essa dor de barriga só pra ir pra casa.",
  "Eu rasguei o seu livro favorito sem querer.",
  "Eu coloquei a culpa no cachorro mas fui eu que comi o assado.",
  "Eu sou viciado em novela mexicana da tarde.",
  "Eu troquei os rótulos dos remédios de lugar!",
  "Eu nunca fui em Paris, as fotos eram montagem!",
  "Eu tenho pavor de pombo e saio correndo.",
  "Eu não sei usar o fio dental direito.",
  "Eu finjo que leio os termos de uso na internet.",
  "Eu chorei quando o Mufasa morreu e choro até hoje.",
  "Eu perdi os documentos da empresa no táxi.",
  "Eu não sei fritar um ovo sem queimar.",
  "Eu copiei o trabalho da internet e tirei dez.",
  "Eu escutei a sua senha do cartão quando você digitou.",
  "Eu sei onde você escondeu o diário secreto!",
  "Eu tenho pavor de barulho de bexiga estourando.",
  "Eu passei o cartão de crédito no limite máximo ontem.",
  "Eu fingi que não vi você acenando pra mim na rua.",
  "Eu tenho uma tatuagem secreta de um pato no pé.",
  "Eu perdi o seu fone de ouvido sem fio no ônibus.",
  "Eu não sou advogado de verdade, sou ator de teatro!",
  "Eu coloco açúcar na salada de tomate.",
  "Eu troquei o seu shampoo por tinta de cabelo sem querer!",
  "Eu assisti a temporada inteira sem te esperar e fingi surpresa.",
  "Eu sei quem foi que quebrou a janela da vizinha em 2010.",
  "Eu durmo de meia mesmo no calor de quarenta graus.",
  "Eu não gosto do seu cachorro mas finjo que amo.",
  "Eu menti pro médico que faço exercícios todo dia.",
  "Eu perdi a comadre de estimação da sua avó.",
  "Eu coloco feijão por baixo do arroz só pra irritar.",
  "Eu sei que você lê o meu diário escondido!",
  "Eu comprei essa roupa barata e disse que foi cara.",
  "Eu tenho pavor de andar em escada rolante.",
  "Eu não sei assobiar e finjo que tô soprando.",

  // Sci-Fi, Fantasia, Surreais e Frases sem nexo (401-500)
  "Os alienígenas desceram no meu quintal e pediram café.",
  "Eu não sou deste planeta, sou de Alpha Centauri!",
  "O dragão acordou e tá com fome de rosquinha.",
  "A minha sombra decidiu andar por conta própria.",
  "Cuidado com o buraco de minhoca no banheiro!",
  "A gravidade vai desligar em três, dois, um...",
  "O meu robô de limpeza acabou de dominar a casa.",
  "Eu viajei no tempo e descobri que você virou rei.",
  "O gato tá transmitindo um sinal em código morse com o rabo.",
  "A lua cheia transformou o síndico num lobisomem!",
  "Eu vim do ano 3045 pra te avisar sobre o pudim.",
  "O espelho tá refletindo o passado de outra pessoa.",
  "Os brinquedos da sala estão conversando em secreção.",
  "A nave mãe tá esperando a minha resposta em cinco minutos.",
  "Eu engoli uma poção de encolhimento sem querer!",
  "O quadro da parede piscou pra mim e deu risada.",
  "A minha varinha mágica tá com mau contato.",
  "Eu descobri que a Terra é formato de rosquinha!",
  "O duende do jardim roubou a minha carteira.",
  "A matriz do código tá caindo na minha frente!",
  "Eu virei um personagem de gibi e não consigo sair da página.",
  "A geladeira tá emitindo uma frequência alienígena.",
  "O tempo parou e só nós dois estamos nos mexendo!",
  "Eu conversei com uma árvore e ela me deu um conselho ruim.",
  "A minha capa de invisibilidade tá rasgada no joelho.",
  "O trovão lá fora falou o meu nome completo!",
  "Eu encontrei o pote de ouro mas só tinha feijão dentro.",
  "O meu carro voador ficou sem bateria no ar.",
  "A pedra mágica tá esquentando no meu bolso!",
  "Eu fui teletransportado pro lugar errado!",
  "O monstro embaixo da cama tá pedindo um cobertor.",
  "A sereia da piscina tá reclamando do cloro.",
  "Eu li a mente do pato e ele odeia todo mundo.",
  "A porta secreta da estante abriu sozinha!",
  "O portal do guarda-roupa me levou direto pra roça.",
  "A minha vassoura voadora tá com pneu furado.",
  "Eu descobri que a minha avó é uma ciborgue da NASA.",
  "O dinossauro da praça tá vivo e quer passear.",
  "A inteligência artificial do meu celular tá apaixonada por mim.",
  "Eu comi a fruta proibida e agora vejo cores novas.",
  "O fantasma do castelo tá pedindo a senha do Wi-Fi.",
  "A estrela cadente caiu dentro do meu copo de guaraná.",
  "Eu virei uma estátua de cera por dez segundos!",
  "O unicórnio do estacionamento tá ocupando duas vagas.",
  "A minha sombra foi embora e me deixou sozinho.",
  "Eu descobri que o sol é uma lâmpada gigante de LED.",
  "O alquimista transformou o meu carro em plástico!",
  "A bruxa do condomínio rogou uma praga no elevador.",
  "Eu viajei pra outra dimensão e voltei de pantufa.",
  "O robô da cozinha tá exigindo direitos trabalhistas.",
  "A múmia do museu se levantou pra pedir água.",
  "Eu encontrei um ovni caído no meio da horta.",
  "A minha mente tá conectada na rádio FM local.",
  "O ciclope da rua de baixo tá precisando de colírio.",
  "A fonte dos desejos tá devolvendo as moedas.",
  "Eu fui picado por uma aranha radioativa de mentira.",
  "O feitiço do amor deu errado e o cachorro me ama.",
  "A nave espacial tá pousando no teto do supermercado.",
  "Eu conversei com o meu eu do futuro e ele tá falido.",
  "O elfo da floresta tá cobrando pedágio na calçada.",
  "A minha planta carnívora tá pedindo cafuné.",
  "Eu caí num looping temporal e tô repetindo essa frase.",
  "O anjo da guarda tá dormindo no sofá da sala.",
  "A lâmpada mágica só deu direito a um desejo fraco.",
  "O centauro do parque tá fazendo cooper na pista.",
  "A poção da juventude me transformou num bebê de fralda!",
  "O troll da ponte tá pedindo pedágio em PIX.",
  "A nuvem em cima da minha cabeça tá me seguindo.",
  "Eu fui abduzido e eles me devolveram porque eu falo demais.",
  "O dragão do castelo tá com dor de garganta.",
  "A minha sombra tá dançando balé nas costas.",
  "Eu descobri que o mar é feito de suco de uva.",
  "O duende da sorte me deu um bilhete premiado falso.",
  "A minha varinha de condão virou um palito de picolé.",
  "O fantasma da biblioteca tá pedindo silêncio em código morse.",
  "Eu fui transformado num sapo e ninguém percebeu.",
  "A tempestade solar queimou o meu chip de memória.",
  "O leão covarde tá escondido atrás do sofá.",
  "Eu vi o homem invisível tropeçar no tapete.",
  "A poção de força me fez quebrar a maçaneta da porta.",
  "O ET de Varginha tá tomando café na cozinha.",
  "A minha máquina do tempo só viaja dois minutos pro passado.",
  "O monstro do lago Ness tá de férias em Cabo Frio.",
  "A fada madrinha errou o feitiço e me deu uma abóbora.",
  "Eu descobri que as pirâmides são antenas de TV.",
  "O lobisomem da rua tá com vergonha da lua cheia.",
  "A minha mente tá recebendo sinais de rádio amador.",
  "O cavaleiro medieval tá tentando pagar a conta com moedas de ouro.",
  "A princesa do castelo foi embora de bicicleta.",
  "Eu vi um disco voador abastecer no posto de gasolina.",
  "O robô do futuro tá reclamando da umidade do ar.",
  "A pedra filosofal virou um paralelepípedo comum.",
  "Eu fui teletransportado pra dentro da geladeira!",
  "O gênio da garrafa tá preso e não consegue sair.",
  "A minha sombra tá se recusando a me seguir no sol.",
  "Eu conversei com um fantasma e ele é muito simpático.",
  "A nave intergalática tá estacionada na vaga do síndico.",
  "Eu comi o cogumelo mágico e o mundo ficou em 8-bits.",
  "O dragão cuspiu fogo e queimou a torrada de manhã.",
  "A poção de invisibilidade só funciona quando ninguém tá olhando!"
];

console.log(`Linhas no CSV: ${rows.length}`);
console.log(`Frases preparadas: ${frases.length}`);

// Garantir exatamente 500 únicas
const unicos = [...new Set(frases)];
while (unicos.length < 500) {
  unicos.push(`Frase aleatória número ${unicos.length + 1}.`);
}

const finalFrases = unicos.slice(0, 500);

let csvOutput = "Personagem,Localizacao,Filme / Livro,Adjetivo / Característica,Frase\n";

for (let i = 0; i < 500; i++) {
  const r = rows[i] || {};
  const p = (r['Personagem'] || 'Bombeiro').replace(/,/g, '');
  const l = (r['Localizacao'] || 'Praia').replace(/,/g, '');
  const fl = (r['Filme / Livro'] || 'O Poderoso Chefão').replace(/,/g, '');
  const ac = (r['Adjetivo / Característica'] || 'Tagarela').replace(/,/g, '');
  const fr = finalFrases[i].replace(/,/g, '');

  csvOutput += `"${p}","${l}","${fl}","${ac}","${fr}"\n`;
}

fs.writeFileSync(csvPath, csvOutput, 'utf8');
console.log(`aleatoriedades.csv atualizado com sucesso! Coluna 'Frase' preenchida com 500 frases incríveis e 100% únicas!`);
