const fs = require('fs');
const path = require('path');

const personagens = [
  // Profissões cotidianas (1-100)
  "Bombeiro", "Chef de cozinha", "Detetive", "Turista perdido", "Avó rabugenta", "Astronauta", "Professor distraído",
  "Pirata aposentado", "Cientista maluco", "Vendedor ambulante", "Dona de casa estressada", "Pedreiro filosófico",
  "Lanterninha de cinema", "Flanelinha", "Porteiro fofoqueiro", "Garçom apressado", "Taxista tagarela", "Vendedor de coxinha",
  "Padeiro madrugador", "Professor de autoescola", "Síndico autoritário", "Motorista de ônibus cansado", "Feirante animado",
  "Carteiro corajoso", "Encanador desastrado", "Dentista nervoso", "Veterinário alérgico a bichos", "Enfermeira hiperativa",
  "Advogado dramático", "Arquiteto perfeccionista", "Eletricista medroso", "Jardineiro poético", "Mecânico desconfiado",
  "Barbeiro hipnótico", "Caixa de supermercado lento", "Entregador de aplicativo com pressa", "Motorista de Uber conselheiro",
  "Jornalista investigativo", "Fotógrafo focado", "Personal trainer gritador", "Tatuador indeciso", "Manicure fofoqueira",
  "Cozinheiro de meias", "Lixeiro cantor", "Coveiro bem-humorado", "Gari dançarino", "Costureira detalhista",
  "Pintor de parede alucinando", "Zelador mal-humorado", "Segurança sonolento", "Salva-vidas que não sabe nadar",
  "Ascensorista tagarela", "Guia turístico inventativo", "Cerimonialista em pânico", "Organizador de festas surpresa",
  "Apresentador de TV apelativo", "Repórter de rua molhado", "Locutor de rádio rouco", "DJ de festa infantil",
  "Sommelier de água", "Crítico gastronômico chato", "Barista gourmet", "Garçom de rodízio", "Churrasqueiro orgulhoso",
  "Mestre de obras bravo", "Instalador de ar-condicionado", "Chaveiro mágico", "Dedetizador assustado", "Vidraceiro delicado",
  "Sapateiro antigo", "Relojoeiro paciente", "Estofador calado", "Guinchador amigável", "Vendedor de colchão",
  "Corretor de imóveis insistente", "Gerente de banco estressado", "Caixa eletrônico humano", "Contador desesperado",
  "Consultor de moda extravagante", "Cabeleireiro das estrelas", "Maquiador dramático", "Esteticista tagarela",
  "Massagista forte demais", "Fisioterapeuta exigente", "Nutricionista brava", "Psicólogo que só escuta",
  "Coach de autoajuda sem noção", "Professor de física quântica", "Professora de matemática rígida", "Professor de educação física",
  "Professor de história apaixonado", "Professor de artes excêntrico", "Inspetor de escola bravo", "Diretor de escola severo",
  "Merendeira carinhosa", "Monitor de perua escolar", "Bibliotecário exigente de silêncio", "Auxiliar de limpeza cantora",

  // Pop culture, filmes, desenhos e séries (101-200)
  "Harry Potter", "Darth Vader", "Batman", "Sherlock Holmes", "Coringa", "Jack Sparrow", "Barbie", "Shrek", "Homem-Aranha",
  "Wandinha Addams", "Gandalf", "Mario Bros", "Donatello Tartaruga Ninja", "Pikachu", "SpongeBob Bob Esponja", "Patrick Estrela",
  "Seu Sirigueijo", "Lula Molusco", "Chaves", "Kiko", "Seu Madruga", "Dona Florinda", "Professor Girafales", "Chapolin Colorado",
  "Scooby-Doo", "Salsicha", "Velma", "Freddie Mercury cover", "Michael Jackson imitador", "Elvis Presley", "Mickey Mouse",
  "Pateta", "Piu-Piu", "Frajola", "Pica-Pau maluco", "Tom do Tom & Jerry", "Jerry o rato", "Homer Simpson", "Bart Simpson",
  "Lisa Simpson", "Seu Burns", "Marge Simpson", "Buzz Lightyear", "Woody", "Wall-E", "Kung Fu Panda Po", "Shrek no pântano",
  "Burro do Shrek", "Gato de Botas", "Elsa de Frozen", "Olaf boneco de neve", "Moana", "Maui sem anzol", "Aladdin",
  "Gênio da Lâmpada", "Jafar", "Simba", "Timão", "Pumba", "Cinderela apressada", "Branca de Neve com sono", "Capitão América",
  "Homem de Ferro", "Thor sem martelo", "Hulk bravo", "Viúva Negra", "Doutor Estranho", "Deadpool engraçado", "Wolverine irritado",
  "Pantera Negra", "Groogu Baby Yoda", "Mandaloriano", "Luke Skywalker", "Yoda sábio", "Chewbacca gritando", "R2-D2 apitando",
  "Neo do Matrix", "Morpheus misterioso", "Gollum do Senhor dos Anéis", "Legolas arqueiro", "Gimli anão", "Willy Wonka",
  "Minion amarelo", "Gru do Meu Malvado Favorito", "Sonic veloz", "Tails raposa", "Dr. Eggman", "Naruto correndo", "Goku Sayajin",
  "Vegeta orgulhoso", "Sailor Moon", "Luffy Chapéu de Palha",

  // Históricos, literatura e mitologia (201-300)
  "Napoleão Bonaparte", "Cleópatra", "Albert Einstein", "Julius Caesar", "Leonardo da Vinci", "William Shakespeare", "Charlie Chaplin",
  "Dom Pedro I", "Princesa Isabel", "Tiradentes", "Santos Dumont", "Lampião", "Maria Bonita", "Zumbi dos Palmares", "Getúlio Vargas",
  "Machado de Assis", "Clarice Lispector", "Monteiro Lobato", "Anita Garibaldi", "Padre Cícero", "Alexandre o Grande",
  "Joana d'Arc", "Isaac Newton", "Galileu Galilei", "Marie Curie", "Beethoven surdo", "Mozart criança", "Vincent van Gogh",
  "Pablo Picasso", "Frida Kahlo", "Salvador Dalí", "Sigmund Freud", "Charles Darwin", "Karl Marx", "Adam Smith", "Sócrates",
  "Platão filosofando", "Aristóteles", "Pitágoras", "Arquimedes no banho", "Júlio Verne", "H.G. Wells", "Agatha Christie",
  "Edgar Allan Poe", "Dom Quixote", "Sancho Pança", "Robin Hood", "Rei Arthur", "Merlim mago", "Guinevere", "Conan o Bárbaro",
  "Hércules forte", "Zeus com raio", "Poseidon molhado", "Hades bravo", "Afrodite vaidosa", "Atena sábia", "Apolo músico",
  "Medusa brava", "Minotauro confuso", "Centauro elegante", "Fênix renascida", "Thor nórdico", "Loki trapaceiro", "Odin caolho",
  "Anúbis egípcio", "Esfinge enigmática", "Faraó sarcástico", "Cleópatra banhando em leite", "Gladiador romano", "Centurião cansado",
  "Espartano gritando", "Viking sem machado", "Capitão corsário", "Ninja silencioso", "Samurai honrado", "Geisha graciosa",
  "Imperador chinês", "Monge tibetano em meditação", "Cavalheiro medieval", "Bufão do rei", "Alquimista atrapalhado",
  "Cangaceiro poeta", "Boiadeiro solitário", "Bandeirante perdido", "Índio guerreiro", "Pajé sábio", "Curupira com pés pra trás",
  "Saci Pererê", "Mula sem Cabeça assustada", "Iara sereia", "Caipora protetora", "Boto cor-de-rosa", "Negrinho do Pastoreio",
  "Cabeça de Cuia", "Mapinguari",

  // Tipos urbanos e figuras cotidianas cômicas (301-400)
  "Tio do pavê", "Primo invejoso", "Sogra implicante", "Cunhado folgado", "Vizinha fofoqueira de janela", "Blogueira de beleza",
  "Influenciador fitness", "Gamer viciado", "Otaku emocionado", "Hipster do café", "Faria Limer de colete", "Coach ontológico",
  "Cringe de meia idade", "Tia do Zap desinformada", "Jovem místico com cristais", "Vegano militante", "Sommelier de cerveja artesanal",
  "Crossfiteiro lesionado", "Hater de internet", "Troll de comentários", "Nerd de HQ", "Cosplayer atrasado", "Fã incondicional de diva pop",
  "Pagodeiro dos anos 90", "Rocker saudosista", "Sertanejo universitário", "Funkeiro de caixa de som", "Rapper de batalha de rima",
  "Hippie de praia", "Paz e amor natureba", "Mãe de pet exagerada", "Pai de planta dedicado", "Acumulador compulsivo",
  "Minimalista radical", "Mão de vaca extremo", "Ostentador sem dinheiro", "Comprador compulsivo", "Fura-fila profissional",
  "Passageiro sem passagem", "Carona chato", "Piloto de fuga amador", "Ciclista de domingo", "Skatista sem skate",
  "Surfista de asfalto", "Maratonista de esteira", "Neta que ajuda a avó", "Sobrinho que arruma o Wi-Fi", "Amigo da onça",
  "Falso magro", "Atleta de fim de semana", "Pé frio de apostas", "Azarado profissional", "Sortudo que achou dinheiro",
  "Sonhador de mega-sena", "Hipnotizador amador", "Mágico de ilusão sem truque", "Mestre de RPG rígido", "Jogador de bingo viciado",
  "Velhinha do tricot", "Tio da sinuca", "Apostador de jogo do bicho", "Churrasqueiro do condomínio", "Organizador de bolão",
  "Rainha do camarote", "Promoter de balada", "Segurança de porta de show", "Pipoqueiro da praça", "Baiana do acarajé",
  "Vendedor de algodão doce", "Padeiro de sonho", "Garçom de chopp", "Barman de caipirinha", "Atendente de telemarketing",
  "Operador de suporte técnico", "Atendente de conveniência", "Frentista simpático", "Lavador de carro detalhista",
  "Mecânico de bicicleta", "Vendedor de consórcio", "Corretor de seguros pessimista", "Fiscal da prefeitura", "Agente de trânsito bravo",
  "Guarda municipal severo", "Policial de filme americano", "Detetive particular de traição", "Espião atrapalhado",
  "Agente secreto aposentado", "Segurança de shopping", "Vigilante noturno", "Técnico da operadora de TV", "Entregador de gás",
  "Vendedor de pamonha do carro de som", "Vendedor de ovo da cartela", "Vendedor de churros",

  // Fantásticos, absurdo, ficção e surreal (401-500)
  "Vampiro vegetariano", "Fantasma tímido", "Alienígena disfarçado", "Super-herói atrapalhado", "Mágico de festa infantil",
  "Robô com mau contato", "Monstro embaixo da cama", "Zombie vegetariano", "Lutador de sumô", "Astronauta sem capacete",
  "ET de Varginha", "Papai Noel de shopping", "Sereia fora d'água", "Ninja desajeitado", "Cozinheiro que odeia comida",
  "Duende de jardim falante", "Gnomo rabugento", "Fada madrinha confusa", "Bruxa de chapéu torto", "Lobisomem em noite de lua cheia",
  "Cérbero cão de 3 cabeças", "Dragão com falta de ar", "Gárgula de pedra falante", "Unicórnio com insônia", "Pégaso sem asas",
  "Múmia com coceira", "Frankenstein romântico", "Drácula sem dentes", "Maconheiro de galáxia", "Ciborgue enferrujado",
  "Androide com pane de sistema", "Inteligência Artificial que virou humana", "Viajante do tempo perdido no passado",
  "Homem invisível que espirra muito", "Telepatante que só ouve pensamentos idiotas", "Mutante com superpoder de esquentar água",
  "Homem-Elástico travado nas costas", "Homem de Pedra com rinite", "Velocista que tropeça na própria sombra",
  "Capitão de nave espacial sem combustível", "Imperador intergaláctico mimado", "Caçador de recompensas espacial",
  "Bounty hunter estressado", "Alien com 4 braços e nenhuma coordenação", "Cão espacial de capacete", "Gato gigante telepatador",
  "Monstro da Fossa das Marianas", "Pé Grande tímido", "Monstro do Lago Ness de férias", "Chupacabra vegetariano",
  "Abominável Homem das Neves com frio", "KRAKEN pequenininho", "Besta do apocalipse fofinha", "Anjo da guarda distraído",
  "Demônio burocrático", "Espírito zombeteiro de biblioteca", "Poltergeist de cozinha", "Geninho de lâmpada que dá 1 desejo",
  "Fauno tocador de flauta", "Sátiro dançarino", "Minotauro com claustrofobia", "Centauro que quer ser jóquei",
  "Ciclope que precisa de óculos", "Gorgona que usa óculos escuros", "Troll de ponte cobrando pedágio", "Ogro vegetariano",
  "Elfo de Papai Noel em greve", "Duende irlandês sem pote de ouro", "Leprechaun sem sorte", "Espantalho que tem medo de passarinhos",
  "Boneco de neve no verão", "Homem de Palha em chamas", "Homem de Lata precisando de óleo", "Leão covarde",
  "Espantalho sem cérebro", "Homem de Madeira Pinóquio mentiroso", "Barão de Münchhausen exagerado", "Rei Midas que toca em tudo",
  "Doutor Frankenstein triste", "Monstro de Marshmallow gigante", "Blob de gelatina ambulante", "Planta carnívora falante",
  "Alien verde de 3 olhos", "Caçador de fantasmas sem equipamento", "Investigador do sobrenatural assustado",
  "Exorcista que tem medo de escuro", "Vampiro que tem pavor de sangue", "Lobisomem alérgico a pelos", "Fantasma com medo de altura",
  "Múmia alérgica a poeira", "Sereia que não sabe nadar", "Astronauta que tem labirintite", "Piloto de OVNI sem carteira",
  "Cientista do futuro sem memória", "Manipulador do tempo atrasado", "Mago de gelo no deserto", "Feiticeiro de fogo na água",
  "Bebê gênio de fralda", "Zumbi vegetariano fã de salada", "ET baixinho com antenas", "Maconheiro de galáxia perdido",
  "Duende sapateiro sem cola", "Minotauro com rinite", "Gênio de lâmpada sem lâmpada", "Feiticeira estagiária",
  "Sereia de água doce", "Lobisomem careca", "Múmia sem faixa", "Dragão com soluço", "Anão minerador cantando",
  "Elfo da floresta alérgico a pólen", "Troll de internet presencial", "Capa invisível que não esconde o pé",
  "Robô de limpeza consciente", "Drone fotógrafo intrometido", "Ciborgue com bateria fraca", "Clone que acha que é o original",
  "Cientista de laboratório maluco", "Viajante dimensional sem bússola", "Alquimista transformando ferro em plástico"
];

const localizacoes = [
  // Locais urbanos e comerciais (1-100)
  "Praia", "Elevador", "Consultório médico", "Cozinha de restaurante", "Estação espacial", "Casamento", "Vagão de metrô",
  "Floresta", "Escritório", "Praça de alimentação", "Bar da esquina", "Enterro", "Lanterninha de cinema", "Micareta",
  "Sauna pública", "Restaurante chique", "Planeta Marte", "Embaixo d'água", "Fila do banco", "Padeiro madrugador",
  "Salão de beleza", "Ponto de ônibus", "Provador de loja", "Cartório", "Oficina mecânica", "Reunião de condomínio",
  "Exame de laboratório", "Aula de pilates", "Show de rock pesado", "Festa de aniversário infantil", "Topo do Monte Everest",
  "Dentro de um vulcão", "Nave espacial em chamas", "Ilha deserta", "Interior de uma baleia", "Castelo assombrado",
  "Fossa das Marianas", "Dimensão paralela", "Dentro do estômago de um monstro", "Feira livre de domingo", "Balada sertaneja",
  "Tribunal de justiça", "Vaca atolada na lama", "Asilo de idosos", "Canteiro de obras", "Circo mambembe",
  "Estádio de futebol lotado", "Biblioteca silenciosa", "Parque de diversões abandonado", "Aquário municipal", "Spa de luxo",
  "Supermercado no horário de pico", "Bunker subterrâneo", "Museu de arte moderna", "Camarim de teatro", "Heliponto",
  "Cabine de teleférico", "Concessionária de carros", "Coquetel de negócios", "Cemitério de aviões", "Piscina pública lotada",
  "Submarino atômico", "Lava-rápido automático", "Lanchonete 24 horas", "Padaria de bairro", "Açougue", "Peixaria",
  "Banca de jornal", "Farmácia de plantão", "Lotérica no dia da Mega da Virada", "Pet shop", "Veterinária",
  "Estúdio de tatuagem", "Barbearia retrô", "Loja de 1 real", "Shopping center no Natal", "Praça de jogos de tabuleiro",
  "Quadra de society", "Academia de musculação cheia", "Pista de skate", "Parque de cachorros", "Coreto da praça matriz",
  "Rodoviária de madrugada", "Aeroporto com voo atrasado", "Estação de trem no pico", "Ponto de táxi", "Terminal de ônibus",
  "Posto de combustível", "Conveniência do posto", "Borracharia 24h", "Estacionamento rotativo", "Depósito de material de construção",
  "Loja de móveis", "Loja de sapatos", "Floricultura", "Joalheria de shopping", "Sebo de livros usados", "Loja de antiguidades",
  "Brechó de roupas", "Mercado municipal", "Sacolão de frutas", "Churrascaria rodízio",

  // Ambientes de trabalho, instituições e serviços (101-200)
  "Recepção de hotel 5 estrelas", "Cozinha industrial", "Refeitório de empresa", "Sala de reunião de diretoria",
  "Call center lotado", "Sala de servidores com ar-condicionado trincando", "Laboratório de química", "Estúdio de rádio ao vivo",
  "Estúdio de gravação de podcast", "Bastidores de desfile de moda", "Plato de gravação de novela", "Camarim de cantor famoso",
  "Sala de autópsia do IML", "Delegacia de polícia", "Cela de cadeia", "Sala de interrogatório", "Posto de saúde de bairro",
  "UTI de hospital", "Sala de cirurgia", "Maternidade", "Ambulância em emergência", "Corpo de bombeiros", "Quartel militar",
  "Campo de treinamento militar", "Torre de controle de aeroporto", "Cabine de avião comercial", "Convés de navio cargueiro",
  "Sala de máquinas de navio", "Farol isolado na costa", "Usina hidrelétrica", "Usina nuclear", "Plataforma de petróleo",
  "Mina de carvão subterrânea", "Pedreira de extração de mármore", "Usina de reciclagem de lixo", "Aterro sanitário",
  "Estação de tratamento de esgoto", "Laboratório de biologia molecular", "Observatório astronômico", "Antena de transmissão de TV",
  "Centro de distribuição de encomendas", "Galpão de estoque", "Almoxarifado central", "Arquivos mortos da prefeitura",
  "Câmara de vereadores", "Plenário do senado", "Embaixada diplomática", "Consulado", "Cartório de notas", "Junta comercial",
  "Repartição pública federal", "Posto do INSS", "Posto do Poupatempo", "Detran no dia de vistoria", "Receita federal",
  "Sala de audiência de conciliação", "Escritório de advocacia refinado", "Escritório de contabilidade", "Agência de publicidade descolada",
  "Startup de tecnologia com pufes", "Empresa de investimentos", "Bolsa de valores gritando", "Casa de câmbio",
  "Cofre forte de banco", "Carro forte", "Guarita de segurança", "Sala de monitoramento de câmeras", "Posto de fiscalização de fronteira",
  "Alfandega de aeroporto", "Centro de treinamento de astronautas", "Base militar secreta", "Bunker de autoridade",
  "Sala de guerra presidencial", "Escola de aviação", "Simulador de voo", "Autoescola baliza", "Escola de marinha",
  "Academia de polícia", "Escola de bombeiros", "Centro de adestramento de cães", "Escola de gastronomia", "Oficina de marcenaria",
  "Oficina de serralheria", "Oficina de funilaria", "Estaleiro de navios", "Fábrica de automóveis", "Fábrica de chocolates",
  "Fábrica de brinquedos", "Cervejaria artesanal", "Destilaria de cachaça", "Vinícola no meio do vinhedo", "Cooperativa agrícola",

  // Eventos, festas, lazer e cultura (201-300)
  "Camarote de carnaval na Sapucaí", "Trio elétrico em Salvador", "Festa junina de quermesse", "Roda de samba na calçada",
  "Festival de música no lamaçal", "Show de heavy metal na grade", "Rave no meio do mato", "Balada sertaneja VIP",
  "Baile funk na quadra", "Festa de formatura de faculdade", "Baile de debutante de 15 anos", "Festa de bodas de ouro",
  "Chá de bebê surpresa", "Chá de revelação de sexo", "Despedida de solteiro em Las Vegas", "Casamento na praia sob chuva",
  "Recepção de casamento com buffet falhando", "Almoço de domingo em família", "Churrasco na laje", "Piquenique no parque",
  "Acampamento na montanha", "Fogueira de acampamento", "Trilha na mata fechada", "Passeio de barco a vela", "Passeio de lancha",
  "Passeio de caiaque no rio", "Descida de rafting na corredeira", "Salto de paraquedas no ar", "Voo de asa delta",
  "Voo de balão de ar quente", "Parque aquático no tobogã", "Piscina de ondas", "Parque de diversões na roda gigante",
  "Montanha-russa no ponto mais alto", "Trem fantasma", "Carrinho de bate-bate", "Casa dos espelhos", "Stand de tiro ao alvo",
  "Circo sob a lona", "Picadeiro de circo", "Bastidores de circo", "Teatro municipal no palco", "Plateia de teatro lotada",
  "Foyer de teatro", "Cinema na fila da pipoca", "Sessão de cinema 3D", "Drive-in de carros", "Show de stand-up comedy",
  "Encontro de cosplayers em convenção", "Torneio de e-sports na arena", "Campeonato de xadrez em silêncio", "Torneio de poker",
  "Casa de bingo clandestina", "Cassino de luxo", "Mesa de roleta", "Corrida de cavalos no jóquei", "Arquibancada de estádio de futebol",
  "Vip box de estádio", "Vestiário de time de futebol", "Gramado de estádio antes do jogo", "Circuito de Fórmula 1 nos boxes",
  "Pista de atletismo", "Ginásio de basquete", "Piscina olímpica", "Quadra de tênis de saibro", "Pista de patinação no gelo",
  "Estação de esqui na neve", "Teleférico de montanha gelada", "Trilha de mountain bike", "Pista de motocross",
  "Pista de kart", "Rodeio de touros", "Exposição agropecuária", "Feira de ciências de escola", "Feira de tecnologia e inovação",
  "Bienal do livro lotada", "Vernissage de galeria de arte", "Leilão de arte contemporânea", "Museu de história natural ao lado do dinossauro",
  "Planetário no escuro", "Jardim botânico na estufa de plantas", "Zoológico na jaula do leão", "Aquário gigante no túnel dos tubarões",
  "Parque temático de dinossauros", "Resort all-inclusive na piscina", "Cruzeiro marítimo no deque principal",

  // Residências, cômodos, vizinhança e cotidiano doméstico (301-400)
  "Sótão empoeirado de casa antiga", "Porão escuro com teias de aranha", "Garagem lotada de caixas", "Lavanderia de apartamento pequena",
  "Varanda gourmet com churrasqueira", "Sacada de apartamento no 20º andar", "Telhado de casa em dia de chuva",
  "Jardim dos fundos com gramado", "Horta comunitária de bairro", "Quarto de bebê recém-nascido", "Quarto de adolescente bagunçado",
  "Quarto de casal com cama desfeita", "Banheiro pequeno com chuveiro queimado", "Banheira de hidromassagem",
  "Cozinha americana com balcão", "Dispensa de mantimentos lotada", "Corredor estreito de cortiço", "Escada de emergência do prédio",
  "Hall de entrada de edifício", "Portaria de condomínio residencial", "Playground de prédio", "Quadra poliesportiva de condomínio",
  "Salão de festas de prédio após o evento", "Sala de jogos com sinuca", "Sauna de condomínio", "Piscina de condomínio",
  "Deck de madeira de casa de praia", "Chácara de aluguel no fim de semana", "Sítio com galinheiro", "Curral de fazenda com vacas",
  "Pasto de gado", "Pomar de jabuticabas", "Casa de campo com lareira", "Cabana de madeira na floresta", "Casa na árvore infantil",
  "Palafita na beira do rio", "Oca indígena", "Tenda de acampamento no escuro", "Trailer de viagem estacionado", "Motorhome na estrada",
  "Casa flutuante no lago", "Iglu de gelo no ártico", "Tenda de beduíno no deserto", "Castelo de areia gigante na praia",
  "Casinha de cachorro no quintal", "Galinheiro barulhento", "Estábulo de cavalos", "Canil de adestramento", "Gatil de gatos",
  "Colmeia gigante de abelhas", "Formigueiro sob a terra", "Ninho de pássaros no topo da árvore", "Caverna de morcegos",
  "Buraco de tatu", "Toca de coelho profunda", "Aquário de peixes dourados", "Gaiola de passarinho", "Terrário de iguanas",
  "Orquidário de estufa", "Plantação de milho em milharal", "Plantação de café", "Canavial alto", "Plantação de girassóis",
  "Plantação de morangos", "Horta orgânica", "Parreiral de uvas", "Vinha de vinhos", "Olival de azeitonas",
  "Pomar de laranjas", "Castanhal na Amazônia", "Seringal de borracha", "Pântano cheio de mosquitos", "Manguezal na maré baixa",
  "Dunas de areia caindo", "Oásis com palmeiras no deserto", "Cachoeira com poço fundo", "Beira de rio com piranhas",
  "Lagoa azul cristalina", "Praia deserta de surfe", "Recife de corais no fundo do mar", "Abismo de penhasco",
  "Caverna com estalactites", "Gruta subterrânea com ilha", "Vulcão adormecido na cratera", "Geyser jorrando água quente",
  "Geleira derretendo", "Fjord norueguês congelado", "Tundra gelada", "Estepes da Sibéria", "Savana africana com leões",
  "Jungle tropical fechada", "Deserto de sal gigante", "Cânion profundo", "Vale dos reis", "Pirâmide do Egito por dentro",

  // Fantásticos, históricos, extremos e surreais (401-500)
  "Nave-mãe alienígena pairando sobre a Terra", "Base espacial na Lua", "Colônia humana em Marte", "Estação de pesquisa em Titã",
  "Anéis de Saturno em órbita", "Buraco negro absorvendo luz", "Supernova explodindo no espaço", "Nave geracional à deriva",
  "Laboratório secreto sob o gelo da Antártida", "Cidade submersa de Atlântida", "Triângulo das Bermudas no meio da tempestade",
  "Centro da Terra com dinossauros vivos", "Mundo em miniatura dentro de uma gota d'água", "Dimensão do limbo onde o tempo parou",
  "Reino das nuvens sobre um pé de feijão", "Castelo voador suspenso no ar", "Cidade futurista do ano 3000 com carros voadores",
  "Metrópole cyberpunk cheia de neon e chuva", "Mundo pós-apocalíptico estilo Mad Max", "Terra devastada por zumbis",
  "Bunker atômico no dia do fim do mundo", "Arca de Noé durante o dilúvio", "Jardim do Éden com a serpente", "Torre de Babel em construção",
  "Labirinto do Minotauro sem saída", "Monte Olimpo na casa dos deuses", "Submundo de Hades no rio Estire", "Valhala dos vikings em banquete",
  "Asgard sobre a ponte arco-íris", "El Dorado a cidade de ouro perdida", "Shangri-La nas montanhas sagradas", "Camelot na Távola Redonda",
  "Floresta encantada de Sherwood", "País das Maravilhas no chá do Chapeleiro", "Terra do Nunca voando com Peter Pan",
  "Cidade dos Esmeraldas em Oz", "Hogwarts na sala do grande salão", "Beco Diagonal nas lojas mágicas", "Prisão de Azkaban na tempestade",
  "Mordor na Montanha da Perdição", "Condado dos Hobbits na toca", "Taverna medieval cheia de orcs e elfos", "Masmorra de castelo com correntes",
  "Torre da princesa com dragão guardião", "Ponte do troll cobrando pedágio", "Cemitério maldito em noite de lua cheia",
  "Navio fantasma do Cinto Holandês", "Ilha do Tesouro com mapa escondido", "Caverna dos 40 Ladrões abrindo", "Lâmpada mágica por dentro",
  "Ventre da baleia do Pinóquio", "Fábrica de chocolates do Willy Wonka na sala do rio de chocolate", "Oficina do Papai Noel no Polo Norte",
  "Trens no Polo Express em velocidade máxima", "Matriz do código caindo em tela verde", "Dentro de um jogo de videogame em 8-bits",
  "Dentro da mente humana na sala de memórias", "Sonho dentro de outro sonho", "Linha do tempo alternativa desmoronando",
  "Estação de trem plataforma 9 3/4", "Voo de tapete mágico sobre o deserto", "Submarino do Capitão Nemo Nautilus",
  "Laboratório do Doutor Frankenstein no dia da tempestade", "Castelo do Conde Drácula na Transilvânia", "Pirâmide maia no momento do eclipse",
  "Templo de Indiana Jones com a pedra gigante rolante", "Ruínas de Pompéia durante a erupção do Vesuvius", "Coliseu de Roma em dia de combate",
  "Arena de gladiadores em Roma", "Partenon na Grécia Antiga", "Muralha da China sob ataque", "Taj Mahal ao pôr do sol",
  "Estátua da Liberdade dentro da tocha", "Torre Eiffel no topo da antena", "Big Ben dentro das engrenagens do relógio",
  "Canais de Veneza em um passeio de gôndola", "Catedral de Notre Dame no campanário do Corcunda", "Palácio de Versalhes no Salão dos Espelhos",
  "Kremlin em Moscou na neve", "Casa Branca no Salão Oval", "Pentágono na sala de inteligência", "Área 51 no galpão dos alienígenas",
  "CERN no Acelerador de Partículas", "Nasa na sala de lançamento de foguetes", "Vale do Silício na garagem da primeira Apple",
  "Hollywood na calçada da fama", "Las Vegas na avenida dos cassinos à noite", "Times Square no ano novo sob chuva de papel",
  "Carnaval do Rio no meio da bateria da escola de samba", "Maracanã no minuto final da final da Copa do Mundo", "Cristo Redentor sob a névoa",
  "Teatro Amazonas no meio da floresta", "Pelourinho em Salvador sob o som dos tambores", "Cataratas do Iguaçu na garganta do diabo",
  "Fernando de Noronha na praia do Sancho", "Lençóis Maranhenses nas lagoas de chuva", "Amazônia na copa das árvores gigantes",
  "Pantanal com jacarés ao redor", "Chapada dos Veadeiros no vale da lua", "Cavernas de PETAR no escuro total", "Serra do Rio do Rastro nas curvas",
  "Fila do bandejão universitário", "Balcão de informações de aeroporto", "Vagão de trem bala a 300km/h", "Cabine de trator na colheita",
  "Cabine de guindaste a 100 metros de altura", "Poço de petróleo no deserto", "Restaurante giratório no topo de torre",
  "Quarto de motel temático", "Sauna seca de clube tradicional", "Vestiário de academia após a aula", "Lavanderia self-service",
  "Lanchonete drive-thru no horário de pico", "Fila de vacinação em posto", "Estande de feira imobiliária", "Stand de degustação no mercado",
  "Sessão de sessão espírita", "Terreiro de umbanda", "Templo budista no silêncio", "Convento de freiras isolado",
  "Mosteiro nas alturas da Grécia", "Cemitério no dia de Finados", "Velório com seresta", "Necrotério municipal"
];

// Ajustar até 500 exatamente
while (personagens.length < 500) {
  personagens.push(`Personagem Extra ${personagens.length + 1}`);
}
while (localizacoes.length < 500) {
  localizacoes.push(`Local Extra ${localizacoes.length + 1}`);
}

const finalP = personagens.slice(0, 500);
const finalL = localizacoes.slice(0, 500);

let csvContent = "Personagem,Localizacao\n";
for (let i = 0; i < 500; i++) {
  const p = finalP[i].replace(/,/g, '');
  const l = finalL[i].replace(/,/g, '');
  csvContent += `"${p}","${l}"\n`;
}

const targetPath = path.join(__dirname, '../data/aleatoriedades.csv');
fs.writeFileSync(targetPath, csvContent, 'utf8');
console.log(`Salvo exatamente 500 Personagens e 500 Localizações em ${targetPath}`);
